#!/bin/bash
# rvs1 cure (in the chain after the merge): two owner items as their own desk rows (F-RES1-3, F-RES1-5) and three ledger findings (F-RES1-1/-6 the assay slice to author, F-RES1-2 the harness, F-RES1-7 the tape bug).
G=$1
node scripts/attended/desk-row.cjs F-RES1-3 "(2026-09-26, from the river-ending-score-1 landing, measured): the RAW River route (the Book's \`e10-river\` boot, not the lever's) has no seams to pan, yet enemies spawn there (2 alive at 11.5 s and at 26.5 s: the spawn edge falls back to west, \`WaveSystem.ts:362\`, and the secure wave defaults to 20, \`Balance.ts:827\`).** A player who reaches the raw route meets bandits on a map with nothing to defend or pan, and a secure there would also satisfy the ceremony's once-guard. Decide: the raw route spawns nothing (recommended; it is the quiet return), or it keeps its waves as an unmarked fight. One word; a contract or WaveSystem slice follows."
node scripts/attended/desk-row.cjs F-RES1-5 "(2026-09-26, from the river-ending-score-1 landing): the River's win is SILENT in the run.** The pan writes the completed score and the Book says 'Secured: wave 0, 5 gold' afterwards, but nothing in the run itself marks the moment (no overlay, no line, no sound), and the Run Ledger (\`RunManager.ts:280\`) never lists the ending. Decide whether the pan gets a small acknowledgement in the run (recommended: one Herald line and the pan's own gold chime, no RunManager secure, which would freeze the sim and offer the Rush) or stays quiet by design. One word; a small src slice follows."
python3 - <<'PY'
p='tasks/BACKLOG.md'; s=open(p,encoding='utf-8').read()
rows=('🟧 **F-RES1-1 + F-RES1-6 — `river-assay-1` TO AUTHOR (game, from the river-ending-score-1 landing 2026-09-26):** the assay cannot replay a River reel: the replay opens the reel\'s own contract (the raw River, no seams; `main.ts:542-543`, `scripts/assay-replay.mjs:58-65`) instead of the ceremony world, reads RunManager\'s `run.secured` and snapshot which the ceremony never sets (`assay-replay.mjs:100`, `:111`; `assay-worker.mjs:132-133`), rounds `timeAlive` to 1e-6, and browser seams follow the `?seed=` pin rather than the run\'s seed (`Game.ts:595` → `HarvestSystem.ts:79` → `Rng.ts:26`; headless `HeadlessContractSim.ts:1100-1105`). Until it lands the River\'s county post stays held (`RIVER_STANDING_POSTS_ENABLED = false`); the slice flips that line last. GATE: a River reel from the spec replays to its own score under the assay worker; every existing pinned floor unchanged.\n'
 '🟨 **F-RES1-7 — TAPE BUG, pre-existing, every contract (from the river-ending-score-1 landing 2026-09-26, measured on base `be37d83cf` and the tip):** a playbook replay that stops before the reel is taken leaves an EMPTY stream on the primary slot and `validateRunTape` refuses the whole reel (`Game.ts:8024`, `RunTape.ts:158`, `:186`, `:518-521`); with the empty streams removed each reel is valid. A player who uses a playbook and stops early loses the reel\'s validity. For the tape and playbook owner; a small `RunTape.ts` slice (drop empty streams at seal). TO AUTHOR after the wave.\n'
 '🟨 **F-RES1-2 — ASTRA HARNESS (from the river-ending-score-1 landing 2026-09-26):** the run-6 play-proofs driver seeds a fabricated waves-30 `e10-river` row (`artifacts/sol/play-proofs/.../driver.ts:72-75`), so a real River completion never reads as new on that seed; the next native River proof must seed no River row. Note for the next Astra master; no action today (A1 parked).\n')
i=s.find('🧭 **OWNER RULINGS 2026-09-26'); assert i>=0; s=s[:i]+rows+s[i:]; open(p,'w',encoding='utf-8').write(s); print('rvs1 ledger rows added')
PY
if ! git diff --quiet -- tasks/BACKLOG.md; then
  git add -- tasks/BACKLOG.md && git commit -q -m "drain: river-ending-score-1 — two owner items as their own desk rows (F-RES1-3 the raw route's stray enemies, F-RES1-5 the silent ending), the assay slice to author (F-RES1-1/-6), the tape bug (F-RES1-7), the harness note (F-RES1-2)

Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" && echo "cure rvs1: desk rows and findings committed $(git rev-parse --short HEAD)" >> "$G" || { echo "cure rvs1: commit failed — needs hands" >> "$G"; exit 1; }
else echo "cure rvs1: rows already present" >> "$G"; fi
