import * as THREE from 'three';

export const Balance = {
  hero: {
    maxHp: 100,
    speed: 6.0,
    accel: 20,
    decel: 28,
    iframes: 0.5,
    radius: 0.5,
  },
  enemy: {
    poolSize: 96,
    hp: 28,
    speed: 2.7,
    speedVariance: 0.1,
    contactDamage: 8,
    contactCooldown: 0.8,
    touchRadius: 0.6,
    separationRadius: 0.9,
    separationRadiusSq: 0.9 * 0.9,
    separationStrength: 0.9,
    spatialHashCellSize: 2,
    spatialHashWorldMin: -40,
    spatialHashWorldMax: 40,
    debugPackSize: 5,
    debugPackRadius: 3.2,
    groundY: 0.05,
  },
  sparkRig: {
    fireRate: 2.0,
    damage: 12,
    range: 10,
    boltSpeed: 18,
    boltRadius: 0.25,
    boltLife: 1.2,
    volley: 1,
  },
  xp: {
    perKill: 3,
    moteMagnetRadius: 2,
    motePool: 64,
    needBase: 12,
  },
  projectile: {
    pool: 128,
  },
  economy: {
    logCapacity: 128,
  },
  goldSeam: {
    activeMin: 2,
    activeMax: 3,
    channelRange: 1.6,
    slowSpeed: 0.35,
    tickSeconds: 1.5,
    tickGold: 5,
    capacity: 30,
    decayMultiplier: 2,
    respawnSeconds: 20,
  },
  camera: {
    fov: 42,
    offset: new THREE.Vector3(0, 22, 14.3),
    lag: 0.08,
    lookAhead: 1.5,
    downScreenLookOffset: 2.2,
  },
  render: {
    exposure: 1.05,
    maxDpr: 2,
  },
} as const;
