import * as THREE from 'three';

export const Balance = {
  hero: {
    maxHp: 100,
    speed: 6.0,
    accel: 20,
    decel: 28,
    iframes: 0.5,
    radius: 0.5,
  },
  enemy: {
    poolSize: 96,
    hp: 25.2,
    speed: 2.7,
    speedVariance: 0.1,
    contactDamage: 8,
    contactCooldown: 0.8,
    touchRadius: 0.6,
    separationRadius: 0.9,
    separationRadiusSq: 0.9 * 0.9,
    separationStrength: 0.9,
    spatialHashCellSize: 2,
    spatialHashWorldMin: -40,
    spatialHashWorldMax: 40,
    debugPackSize: 5,
    debugPackRadius: 3.2,
    groundY: 0.05,
  },
  waves: {
    graceSeconds: 5,
    trickleInterval: 2.4,
    trickleDecay: 0.97,
    trickleDecayEvery: 10,
    trickleFloor: 0.8,
    waveInterval: 30,
    pulseBase: 3,
    pulsePerWave: 3,
    kneeWave: 10,
    kneeSharpness: 8,
    budgetCeiling: 42,
    lullSeconds: 8,
    lullFloor12: 8,
    pulsesPerWave: 2,
    edgesPerPulse: 2,
    hpScalePerWave: 1.12,
    speedScalePerWave: 1.02,
    speedScaleCap: 1.3,
    aliveCap: 60,
    spawnRingRadius: 26,
    pressureBudgetShared: true,
  },
  sparkRig: {
    fireRate: 2.0,
    damage: 12,
    range: 10,
    boltSpeed: 18,
    boltRadius: 0.25,
    boltLife: 1.2,
    volley: 1,
  },
  blast: {
    damage: 20,
    dmgPerWave: 0.28,
    radius: 2.2,
    cooldown: 2.5,
    airTime: 0.7,
    range: 10,
    pool: 8,
    volley: 1,
  },
  xp: {
    perKill: 4,
    moteMagnetRadius: 2,
    motePool: 64,
    expiryBanks: true,
    needBase: 12,
    needStep: 8,
  },
  projectile: {
    pool: 128,
  },
  beacon: {
    costBase: 25,
    costGrowth: 1.3,
    maxCount: 6,
    // Wave-18 correction: 10 base + 0.75/wave keeps two beacons relevant at wave 10
    // without changing targeting or hero Spark Rig damage.
    damage: 10,
    damagePerWave: 0.75,
    fireRate: 1.2,
    range: 8,
    boltSpeed: 14,
    volley: 1,
    placeRadius: 6,
    overlapRadius: 1.2,
    gridSnap: 1,
  },
  turret: {
    costBase: 50,
    costGrowth: 1.35,
    maxCount: 4,
    damage: 52,
    fireRate: 1.1,
    range: 16,
    boltSpeed: 16,
    volley: 1,
    placeRadius: 6,
    overlapRadius: 1.2,
    gridSnap: 1,
  },
  palisade: {
    cost: 10,
    maxCount: 48,
    width: 1,
    depth: 3,
    overlapRadius: 1,
    avoidancePad: 0.68,
    slideBias: 0.82,
  },
  sluice: {
    cost: 40,
    maxCount: 3,
    riverPad: 2,
    cycleSeconds: 5,
    goldPerCycle: 3,
    contestedRadius: 6,
  },
  stockpile: {
    cost: 60,
    maxCount: 2,
    capBonus: 150,
  },
  steal: {
    share: 0.25,
    minWave: 3,
    grabAmount: 10,
    grabSeconds: 0.8,
    fleeSpeedMult: 1.35,
    grabRadius: 0.9,
    pickupCap: 24,
    maxConcurrent: 2,
    maxConcurrentPerWaves: 6,
    maxConcurrentCap: 4,
    reclaimStockpileBonus: 0.25,
    pingSeconds: 3,
  },
  repair: {
    pctOfCost: 0.25,
    capPctOfCost: 0.4,
  },
  wreck: {
    hp: {
      sentry_beacon: 40,
      palisade: 60,
      sluice: 40,
      stockpile: 80,
      turret: 50,
    },
    hpWaveScale: {
      sentry_beacon: {
        perWave: 6,
        startWave: 6,
        capMult: 3,
      },
      palisade: {
        perWave: 8,
        startWave: 6,
        capMult: 3,
      },
      turret: {
        perWave: 8,
        startWave: 6,
        capMult: 3,
      },
    },
    damage: 8,
    hitCooldown: 0.9,
    reach: 1.1,
    share: 0.25,
    pulseEvery: 2,
    minWave: 4,
    repairSeconds: 1.2,
    repairCostFrac: 0.3,
    repairRadius: 1.4,
  },
  economy: {
    logCapacity: 2048,
    bankCap: 200,
  },
  upgrades: {
    assayGoldPerWave: 5,
    fieldDressingHealFrac: 0.3,
  },
  offers: {
    investBonus: 0.35,
  },
  goldSeam: {
    activeMin: 2,
    activeMax: 3,
    channelRange: 1.6,
    slowSpeed: 0.35,
    tickSeconds: 1.5,
    tickGold: 5,
    capacity: 30,
    decayMultiplier: 2,
    respawnSeconds: 20,
  },
  camera: {
    fov: 42,
    offset: new THREE.Vector3(0, 26.2, 18.3),
    lag: 0.15,
    lookAhead: 1.35,
    downScreenLookOffset: 3.35,
  },
  render: {
    exposure: 0.75,
    maxDpr: 2,
  },
  terrain: {
    featureMix: 0.86,
  },
  sprite: {
    turnRateDegPerS: 540,
    orientationFadeMs: 100,
  },
  charm: {
    hitPauseMs: 30,
    hitPauseCooldownMs: 250,
    camImpulse: 0,
    coinTick: 1,
    banterCooldownS: 8,
  },
} as const;
