// s1491 handoff — replace line-1, archive the lock line as a bullet, verify the s1490 handoff
// archive survived (§4: check the END STATE, do not assume the tooling did it).
import { readFileSync, writeFileSync } from 'node:fs';

const p = 'STATUS.md';
const lines = readFileSync(p, 'utf8').split('\n');
const lock = lines[0];
if (!lock.startsWith('Last updated: ACTIVE') || !lock.includes('s1491')) {
  throw new Error(`line-1 is not my lock line: ${lock.slice(0, 90)}`);
}

const handoff =
  'Last updated: 2026-08-06T17:38Z s1491 handoff, lock CLEARED — 🟩 **NO DRAIN EXISTED, SO I TOOK THE TOP OPEN FINDING — AND IT TURNED OUT TO BE FALSE. F-1489-1 IS CLOSED BY REFUTATION: THE "DECAYED" DISCRIMINATOR STILL WORKS, AND THE BISECT ITS GATE ORDERED WOULD HAVE CONVICTED AN INNOCENT COMMIT.** ' +
  '🔻 **BOARD AT LOCK, VERIFIED NOT INHERITED:** 6 queues empty, newest done-move already drained (`b039739e1`), no unshipped `failed/`, no `CODEX-WALL`, assayer pending **0**, `ticker-digest-2026-08-05` already filed. `lane-a` **BUSY** (the attended seed-1 dispatch, runner claimed 16:27); `lane-b/c/d` **USABLE** but all **83 behind** with `package.json` in the run-surface drift. The fires-only E3 ladder still ends at `e3-fairground-socket`, `blockClass: owner-fork` on **F-1475-1**. **0 drains available, 0 of 3 budget used. PIPELINE-DRY (fire side) stands, unchanged.** ' +
  '✅ **F-1489-1 CLOSED — `ec81324fc`.** s1489 filed it as *"the quiet-GREEN discriminator has decayed — it now reds quiet on both trees"*, and asked the next fire to bisect when that property was lost. **It was never lost.** F-1146-6’s recipe executed **verbatim** on `2895ab088` returns its documented result exactly: `-g "warmed test clip swaps" --repeat-each=3` → **3/3 PASS desktop, 3/3 PASS mobile**; across four quiet-arm runs **18 of 20 instances PASS**. The contended half reproduces too — the **3-spec battery** (the composition s1489’s own evidence table names at `reviews/f1486-1.md:29`) went **RED 2 of 2 runs** at `:461`. ⭐ **So the contended-RED / quiet-GREEN fingerprint is INTACT IN BOTH DIRECTIONS and the next fire CAN retire this red the documented way** — the clearance path reported as unavailable is available. ' +
  '🔬 **THE DURABLE HALF IS THAT I KILLED TWO OF MY OWN EXPLANATIONS WITH MY OWN DATA.** (1) *Composition is the discriminator* — it fit runs 1–4 and explained s1489 elegantly as a conflation of two meanings of "isolated" (composition-isolated via `-g` vs a quiet box); **killed by run 5**, an isolated run that reddened. (2) *A cold dev server is the discriminator* — genuinely seductive: both reds were `repeat1`, the FIRST instance of each project, greening on repeats 2–3, and mobile’s **61→62** is *exactly* s1489’s number; **killed by run 6**, same cold arrangement, 6/6 green. **Neither survived a re-run of its own arrangement, and both would have shipped as confident findings had I stopped one run earlier.** The house law about re-running before blaming a number is usually aimed at the subject; here it caught **my own hypotheses**, twice in one session. ' +
  '📐 **WHY THE ORDERED BISECT WAS THE WRONG INSTRUMENT, now measured rather than cited:** quiet-arm the predicate is **non-deterministic** (18/20) so a step flips on noise; battery-arm it is red at current main **and** was red at pre-merge main (s1489’s own control), i.e. **all-BAD**, which converges on an innocent commit by construction. ⚠️ **A GATE can order an impossible act in good faith — this one did, and following it literally would have produced a confident, wrong culprit.** ' +
  '🏷️ **NAMED CAUSE (the GATE’s second branch, satisfied):** a load- and arrangement-sensitive flake unchanged in kind since F-1136-1 — the harness’s own comment records boot-time lazy uploads "land for seconds and vary run-to-run", so under load exactly one crosses the `baseline`/`after` boundary. Hence the eternal **+1**, its migration between asserts, and counts drifting up as the game grows (desktop 30→32→84). **NOT a regression, NOT a re-pin candidate, owned by no commit.** ' +
  '⚠️ **CORRECTION THAT OUTLIVES THIS FINDING: `:461` AND `:467` ARE DIFFERENT QUANTITIES, AND EVERY WRITE-UP OF THIS CLASS SINCE F-1136-1 HAS COLLAPSED THEM INTO ONE "OFF-BY-ONE".** `:461` is `expect(afterTextures)`, `:467` is `expect(afterCalls)`. Because an early assertion disables what follows, a desktop `:461` red means **`:467` was never evaluated** — so "both projects, same signature" was always two different measurements wearing one label. ' +
  '📌 **BOOKKEEPING:** the re-validated recipe is written onto the **F-1146-6 known-red row itself** (the row a future fire actually greps, not the closed finding), including the operational meaning of "isolated" and the ready-made predicate `node artifacts/f1489-1/probe.mjs --cwd <wt> --port <scratch> [--battery] [--repeat 3]` — kept as ONE file so the predicate cannot drift between runs. The halo leaf’s note in `tasks/goals.json` asserted the refuted claim as fact and is corrected. s1489’s original row is retained verbatim as a superseded sub-line, not deleted. 🗄️ **RETENTION CATCH:** `.gitignore:7` (`*.log`) would have left all three cited evidence logs **untracked and dying with the disk** while two ledger rows pointed at them — renamed to `.txt` and every citation repaired **in the same commit**, since a cure that rots its own evidence pointers is a known house failure. ' +
  '🧪 Measured in detached worktree `gate-s1491` on scratch port **5234** — never main’s tree (§3.0b), never 5188 (`lane-a` BUSY holds it under `strictPort`), `--workers=1` throughout (§3.1), **with a Codex lane running the whole time — so the green arms greened under MORE load than the control that reported them red.** Worktree and server cleaned up; `gate-s1455/` left alone (not mine). No deploy: bookkeeping-only fire, no gameplay code merged. ' +
  '📌 **NEXT: (A)** F-1489-3’s last open conjunct is still free — the next fire that merges gameplay code and deploys should confirm `asset budget <project>: <n> bytes` in `logs/deploy.log` (expect ≈20.1 MB of 25 MB). **(B)** the board’s fire-side throughput is now gated **entirely** on **F-1475-1**: with F-1489-1 closed there is no unblocked fire-actionable finding left, the E3 ladder’s last rung is owner-forked, and lanes b/c/d need a refresh before they can take anything. **(C)** if the owner rules F-1475-1, refresh b/c/d (83 behind, `package.json` drift) and refill. **(D)** I authored no master: the one ladder open to fires is owner-blocked and §2E forbids inventing scope to avoid waiting. ' +
  '🔺 **OWNER’S DESK — 10 awaiting a word, 0 new this fire.** 🔺 **F-1475-1** — the highest-leverage word and now the *only* thing gating fire-side throughput: `SUPPORTED_CONTRACTS` walls **30 of 42** contracts, so one ruling unblocks `e3-fairground`, the 10 blocked E7/E8/E9 rows, **and the fires’ only ladder.** **RECOMMENDED (c):** a diagnostics-only boot flag that bypasses the support gate for MEASUREMENT while leaving `SUPPORTED_CONTRACTS` — the playability CLAIM — untouched. · 🔺 **F-1485-1** — survives only for the 8 `feral_terraformer` cells; binding conjunct is the pocket baseline, not the 1/255 threshold. Blocks nothing. · 🔺 **F-1477-1** — tracked screenshot evidence churns 100% of the time (0/10 byte-stable); **RECOMMENDED: keep tracked and exempt `artifacts/**` from the pre-flight clean test.** · 🔻 **F-1473-2** — three gate-cost rulings, one word each: root `halo-reextraction-check.mjs` into `test:node-guards` (+45.3 s; s1470/s1473/s1487/s1489 all recommend **YES**, and it is the sole acceptance test of SHIPPED work)? Root `npm:test:asset-diet` (+52.3 s)? Root `npm:test:release` (~200 s, sole gate over the E1 release door)? · 🟡 **F-1472-1 — VETO WINDOW STILL OPEN.** · 🟡 **F-1470-4** — (A) 64 + (B) 192 cells, the honest eye-gated residue. · 🟡 **F-1462-1** — the two ER-02 rulings. · 🟡 **F-1461-6** — gates E7–E10; those four censuses have MERGED. · 🟥 **F-1461-1** · 🟥 **F-1461-5** — runner-side, attended, inert until the runner restarts. ' +
  'ⓘ **Robin owes** (unchanged this fire, nothing delivered or newly emerged): the F-1473-2 gate-cost words, the F-1475-1 ruling, the F-1462-1 ER-02 rulings, and the F-1461-6 E7–E10 word.';

lines[0] = handoff;
lines.splice(1, 0, `- **s1491 lock line (archived):** ${lock}`);

const out = lines.join('\n');
writeFileSync(p, out);

// §4 duty is about the END STATE — verify, do not assume.
const archived = (out.match(/s1490 handoff \(line-1 archive\)/g) || []).length;
console.log(`s1490 handoff archive bullets: ${archived} (expect 1)`);
if (archived !== 1) throw new Error('s1490 handoff archive missing or duplicated');
console.log('handoff written; lock line archived');
