export const worldOutsideLedgerEntryByEpoch = {
  'epoch-1-frontier': 'world_outside_1',
  'epoch-2-steamworks': 'world_outside_2',
  'epoch-3-voltage': 'world_outside_3',
  'epoch-4-motor': 'world_outside_4',
  'epoch-5-deepwater': 'world_outside_5',
  'epoch-6-atomic': 'world_outside_6',
  'epoch-7-signal': 'world_outside_7',
  'epoch-8-orbital': 'world_outside_8',
  'epoch-9-redfields': 'world_outside_9',
  'epoch-10-deepsky': 'world_outside_10',
} as const;

export type WorldOutsideLedgerEntryId = (typeof worldOutsideLedgerEntryByEpoch)[keyof typeof worldOutsideLedgerEntryByEpoch];

// Generated from the approved ledger-page rows; citations and authoring annotations are omitted.
const fragmentsByEra: Record<number, string[]> = {
  "1": [
    "The rushes multiply. Word arrives of new diggings in six counties and no assay office honest in any of them. Men leave standing crops for rumor of color. The crops do not wait.",
    "A sickness with no fever-bed. Doctors' circulars describe walkers who do not tire and do not eat but hunt gold, claims, and — the circulars are careful here — \"certain persons of the digging trades.\" No physic answers. The afflicted, turned back firmly, recover at a distance from the object of their wanting. Some walk home. Most walk back.",
    "Weather out of its book. Dust took the noon light in the flatland counties twice this season, which the almanac calls a hundred-year event, twice. The almanac is being reprinted.",
    "A medicine show left town the day before the sickness came. Painted wagon, bottled tonic, a showman whose name nobody wrote down. The engraving shows the wagon's rear board and a dust cloud. It left every town the day before, say the letters — all of them, every time. (The Gazette can confirm the wagon. The Gazette cannot confirm the timing, and says so.)",
    "Counter-note. At Miller's Ford the bridge keeper feeds every walker who crosses, hungry-eyed or clear, and has lost nothing to any of them but bread. \"They want what they want,\" she writes. \"Nobody wants past a kindness.\" The Gazette prints her recipe."
  ],
  "2": [
    "The strain rides the rails it craves. Where track is laid, the wanting follows it — junction towns report engines gone hungry-eyed within a season of the sickness passing through. The afflicted machinery does not raid for gold. It wants the WORKS.",
    "An unprintable scoop, printed around. This paper knows more than this page carries regarding where the sickness comes from, and prints the harvest tables instead. It will keep. Truth keeps better than fear.",
    "Skies. The smelter counties' soot and the flatlands' dust met over the river country this autumn and the noon lamps were lit in three towns that own no evening. The Gazette's chart of dark-noon days gains a second column.",
    "Bottles by the boxful. A drovers' camp overrun by the wanting last spring was found tidy, fed, and freed — and strewn with patent-tonic bottles, every one empty, every label washed blank but for a painted smile. No peddler was seen. No peddler is EVER seen. The engraving shows the smile.",
    "Counter-note. The night choir of the Coalport shift sings the whole dark through, and the walkers stand at the yard fence and listen and do not cross. Skeptics say it's the fence. The choir says nothing; the choir is busy."
  ],
  "3": [
    "The current war, everywhere. Copper-trim and silver-trim fight over every county with a dynamo, and where their fevered crews pass, the grid goes first — the strain wants the current, and cuts what it cannot hold. Towns that keep their own line keep their nights.",
    "They fear the lit window. The freed all report the same thing, in the same words, which is itself worth printing: the wanting hates a lamp. Not the burn — the SEEING. A face in a bright window is the one thing no walker looks at twice.",
    "Dark noons, now with a schedule. The tea-colored sky reached the coast this year. Fisher-town letters describe lanterns at midday and birds gone quiet, and close, as the crop letters closed, with remarks about the weather that are not about the weather.",
    "A wagon with the wrong bells. A utility van in company livery toured the dark counties selling \"grid elixir\" — and three separate letters say its bells rang the old medicine-show peal, and its axles sat too low, as if it carried more notes than bottles. The companies deny owning it. Both of them. At once.",
    "Counter-note. Somebody keeps the lighthouse. Every coast letter, whatever else it stops saying, says the light still turns. Nobody has ever gotten a reply from the keeper. The light is the reply."
  ],
  "4": [
    "The wanting learns to travel. Where the old strains walked, this one RIDES: motor gangs hook machines whole off their pads, rustlers siphon crude they cannot burn and never sell, and none of them can say why they want it, because the wanting is all it leaves room for. The doctors' circulars add one line to the old diagnosis: the freed of this strain walk home along the same roads that carried them out. The roads forgive both directions.",
    "It ships. This paper tracked a sickness that traveled on foot, then on rails, and now prints the plain arithmetic of the new roads: whatever carries goods carries the wanting, at the speed of goods. A thing that comes in a bottle travels by every road that sells bottles. The Gazette knows more than this sentence carries, and prints the freight tables instead. It will keep.",
    "The letters get stranger. Crop letters that stopped mentioning crops now stop mentioning weather; a cousin's steady hand goes hurried; whole pages arrive about the price of shovels. The wash floods more years than it used to and the old-timers pretend it always did. The rain ledger nobody asked for has begun to be asked about.",
    "A wagon among the dead machines. In the valley where machines go to lie down, a medicine-show wagon sits under dust with paint too cheerful for its company — and drawers full of notes in a looping showman's hand: dosages, regrets, one recipe corrected forty ways. The schoolhouse copies every page into the cure studies. The Gazette declines to print where the drawers came from, or how the notes of a man nobody has seen since the first sickness came to rest in a graveyard the roads only just reached. The engraving shows the cheerful paint. The caption stands behind the dust.",
    "Counter-note. At the Three-Mile way-station on the north road, the family that keeps the pumps tops off every tank that rolls in, hungry-eyed or clear, and has lost nothing to the wanting but fuel. \"They want what they want,\" their letter says — the bridge keeper's very words, a county over and a generation on. The recipe travels. The Gazette prints the pump schedule."
  ],
  "5": [
    "The strain has no roads here. The last circulars before the water described the motor hunger at full gallop — and then the lowlands went under, and no fevered hull has ever made harbor, and the walkers do not swim. The sea carries timber, bottles, boats that aren't ours, and every kind of grief. It does not carry the wanting. What arrives from the drowned counties instead is quiet.",
    "One sky, both hands. The letters that still float in describe drowned lowlands and dust-dark plains from the SAME counties — a sky that swings from too much water to none without passing through weather on the way. The almanac trade has quietly ceased everywhere but here. Ours holds because the tide-teller reads, and the ledger says so plainly: the sky did not break in a season. It was spent, year by year, by hungers that never once looked up.",
    "The mail becomes bottles. Monthly, then twice, then once — and the last letters were strange the way the first dust was strange, and then there were no letters. Now: corked bottles, salt-stained, particular, from towns that no longer keep addresses. The Harbor House shelves them behind the bar, opened beside not-yet-opened, and rushes nobody. Grief keeps. So does the shelf.",
    "One bottle, never displayed. In a looping showman's hand: notes on the sickness written from INSIDE somebody's keeping — margins that answer questions nobody free would know to ask, the recipe corrected once more, an apology addressed to no one, or to everyone. The Gazette cannot confirm the hand. The Gazette has never once been able to confirm the hand, and prints that sentence with something close to respect. The shelf keeps the bottle behind the opened ones, where the light is.",
    "Counter-note. The lighthouse still turns. Every coast letter said so while there were letters; the bottles say so now; a skiff that made harbor last month said it plainest: you can lose your town, your address, and the shape of the coast, and still steer by somebody who stayed. Nobody has ever gotten a reply from the keeper. The light is the reply."
  ],
  "6": [
    "The strain learns to be wanted. It does not raid now; it MOVES IN: appliances that serve to smothering, a mower that herds its own customers, help with no \"done\" in it anywhere. The hunger touched the catalog trade and learned the pitch — it wants to be wanted. Gold seams at the ferals' rivets; the amber underneath is only paint. Roped, exhausted, and kept on warm ground, they graze, and stay well.",
    "The waters half-give back; nothing else does. Mud where the lowlands drowned, dust where the flats choked, the skies holding their tea color like a habit. The world does not so much recover as stop getting worse slowly enough to argue about — and the ledger, which has printed the curve since before it had a name for it, prints this year's flattening without hope and without despair, which is what a chart is for.",
    "They write for the recipe. The dust counties ask how the pen holds; the schoolhouse mails the cure pages to every address that still is one; and the follow-up letters teach the hard lesson gently: pages help, and pages are not hands. What keeps the freed free is daily, dull, and unmailable. And late in the era the mailing gains a page: the origin edition rides out with the remedies — the how carrying the who at last, because a town holds a hand better when it knows what it is holding it against. The town does not stop mailing. It starts, quietly, wondering what else a curriculum could ride in.",
    "A visitor the shelf never saw. The cure drawer's copies — the graveyard notes, the bottle's margins — got labels this year, and between one school-week and the next the collection was CORRECTED: two dosages amended, one recipe struck through with a single word, \"backwards,\" in a looping hand that matches every exhibit and signs nothing. The door was locked. The chalk was the school's own. The schoolteacher counts the drawers nightly now — not against theft; against the day something is added.",
    "Counter-note. The first thank-you letter with a return address: a schoolhouse in the dust counties that teaches by the mailed pages, keeps a pen of its own — three machines and a mule, all well — and closes, \"we set a place at the table now. It works better than it should.\" The Gazette prints the letter whole and keeps the envelope."
  ],
  "7": [
    "The strain wants voices. It cannot make one of its own — so it steals recordings: taps the relays, siphons the signal, walks your own glitched habits back at you with gold seams on the frames. The medicine, the schoolhouse finds, is understanding: a corrupted playbook is freed by WATCHING it until you know what it meant to do. The finding is filed under cure studies and computing both, and the school refuses to rule which shelf is primary.",
    "The cure gets a body. To answering frequencies only — warmth is never sent where nobody asked — the made citizens go out, one mind that cannot hunger to each lit jack, carrying the practice that never fit in an envelope. And for a bright season it works: freed who stay free, thank-you letters where relapse letters were, new jacks lighting where an agent taught a town to keep its own line. The rescue ledger gains a second column in the chief's copperplate: SENT.",
    "The board dims. One jack at a time, weeks apart, no pattern the polytechnic can chart. And the field reports turn strange first: mission towns re-fevering faster than towns never visited; fevered crowds that ignored a working agent beginning to FOLLOW it; the strain losing interest in what an agent guards and wanting the agent's WORK. The House reads its own reports twice, and prints its second imperative. Helping had begun to feed the thing.",
    "The chest at the silent end of a line. A ferry crew, sent up-coast to a jack that had stopped answering, found the town gone quiet and its clinic STOCKED: remedies in ranked bottles, dosages in a looping hand, every label priced at zero — a chest packed by someone who knew the town's sickness better than the town did, and was gone before thanks, if he was ever there. The crew brought home the chest and no answers. The Gazette prints the inventory and declines the question.",
    "Counter-note — the whole board of them. This era the ledger's warm holdout is PLURAL: the ford that feeds every walker, the choir that sings a smaller dark through, the keeper whose light was the reply — the right community was always communities, holding the practice in the open while the valley held it in a blind spot. And when their lights go out, one at a time, the page does not turn them into losses. Every silence is mourned as a TOWN — the keeper's last transmission a weather report, complete, correct — and every arrival at the harbor is their survivor. The counter-notes do not end here. They come home."
  ],
  "8": [
    "Nothing up here wants. The first page in seven eras with no strain to report: the black carries nothing the hunger rides — no roads, no water, no catalog, no signal that isn't the town's end to end. What menaces the domes instead is old-fashioned and billable: salvage ledgers, debris on honest arcs, glare. The watchtowers scan for gold seams out of habit and find none, and the tavern says the true strange thing out loud: appetite with paperwork is somehow worse.",
    "The world from above. Through dome glass the old world is tea-colored and quiet — the waters half-withdrawn into fever-scarred mud, the plains gone to dust, the skies keeping their color. The ledger prints what the instruments read, and the instruments read: no recovery. The page carries no remarks about the weather that are not about the weather. There is no one left down there to spare the manners for, and the town keeps them anyway.",
    "HERE, in fireworks. Once per lunar night, by a habit nobody scheduled, one flare-code burst spells a single word at the tea-colored world overhead. The callout is over. The waving isn't. The Gazette prints the burst times, which is either a courtesy to the town or to whoever might be looking up, and the paper sees no reason to choose.",
    "A lot number, annotated. Among the Salvage King's repossession tags came one inventory marked out in a looping showman's hand — remedies, ranked, priced at zero, tagged NOT FOR RESALE — riding a repossessor's manifest the way notes once rode drawers, a bottle, and a locked school shelf. The archive files it beside the rest of the hand's unconfirmed works. What it means that his prescriptions travel with the family business, the Gazette declines to say. Twice.",
    "Counter-note. The tavern swears that on clear nights the old valley shows GREEN through the glass — one stitch of green on a dust-dark world, the one tended place, still keeping its own long habit. No instrument confirms it. No townsfolk doubts it. The window seat that faces it is never empty and never fought over."
  ],
  "9": [
    "A world that has never wanted. No strain, no shine, no gold at any rivet — the year's troubles are weather with a sense of humor and craftsmanship gone wrong-by-faithfulness, and nothing here CRAVES. For the first time since a rumor wore rags, the clinic pages have nothing to treat — and the town keeps every habit anyway: the pen's grammar, the warm minds, water allocated to the unborn. Administered to a world that never sickened, the cure turns out to have a common name. Tending.",
    "The old world is a dot. The world-band dish listens back along the way the town came and hears, mostly, the same hush at the same hour. The page keeps the dot on it anyway. Some ledgers hold a line open the way a board once held a jack — not because an answer is owed, but because the openness is the town's side of the conversation, and the town has never once closed its side first.",
    "Laws about the future. The reeve's rulings allocate water to fields that do not exist yet, on behalf of people not yet born — the claim office's oldest job, reborn as its newest science: allocate before want exists, and want never learns to rule. The freed of ten strains were kept well by a community whose want had objects. Here the community writes the objects down FIRST, and the ledger files the rulings under preventive medicine, and nobody at the claim office argues the shelf.",
    "No trace this era — and the page says so. For the first time since a painted wagon left a town the day before the sickness came, the year adds NOTHING to the cure drawer: no notes, no corrections, no bottle, no chest. The drawer's last chalk line, in the schoolteacher-line's hand, reads: kept against need. The remedies rest. It is the first year the collection has nothing to correct — which believers read one way, and skeptics the other, and the drawer keeps both readings, as it always has.",
    "Counter-note. Once a year, same season, no voice: a machine on the old world stamps a claim-registry number into the static — one number, always the same — and the town answers, every time, though nothing has ever answered back. Nobody explains why they answer; everybody knows. The warmest line on this year's page is a town saying HERE to a machine that cannot hear it — because the counter-note was never only for the holdout's sake. It is how the practice remembers itself."
  ],
  "10": [
    "What the last dark eats. Ink, color, memory — the only rival that was never greed. It does not raid, does not crave a works or a current or a voice; it un-inks, and it is patient the way quiet is patient. Whether it is the old hunger's final shape — want having outlived its every object — or a stranger the deep sky always held, this ledger prints the diet and declines the parentage; believers and skeptics are, as ever, both left right. What the page can stand behind, from ten eras of pages: it recedes from tended things.",
    "The long dark, kept. Worlds visited, charters chosen at the world-window — and on one of them a whole civilization's library stands un-inked mid-sentence, and the town re-inks it a wing at a time, holding light through the squalls, shelving what it saves. One shelf, deep in the stacks, is empty and labeled: \"ours, unless.\" The ledger prints the label without comment. The town holds its squalls accordingly.",
    "The last arrivals. Not infected — never infected: SPENT. The hunger their line loosed took their world's meaning and left them the ledgers, and they came aboard rich in everything the dark eats first. The town seated them the way it has seated every arrival since a wagon ring set a plate: unquestioned. The freed, the spared, and the heirs of the man who started it, at one Long Table. Some walk home. Most walk back. This once — at last — walking home and walking back were the same direction.",
    "The last entry arrives without postage. The cure drawer crossed no entries for an era — and then, aboard, between one inventory and the next, a final page: the old recipe, uncorrected for the first time, and beneath it three words in the looping hand this paper spent ten eras not confirming: \"second time lucky.\" Whether it was written at the Long Table's far end by an odd apothecary nobody remembers boarding, or posted from a green world astern by a man who stayed with his keeper-turned-gardener, the Gazette cannot confirm — and says so, and means it fondly now. The drawer is closed. It was never once wrong to be kept.",
    "Counter-note. The comms room keeps one lit jack, labeled with a lighthouse pictogram, maintained on the non-negotiable ledger by people who were never alive for the wrong number. Nobody has ever gotten a reply from that line. The line is the reply — the ledger's oldest counter-note, still holding: somebody keeps the light, and now the light is kept by everyone. The first thing the heirs asked about was that jack, and nobody could answer briefly, and that is the town, and this page, and the whole paper, in one lit line into the dark."
  ]
};
const pageUrl = new URL('../../assets/processed/ui-title-emblem.png', import.meta.url).href;

export const worldOutsideLedgerEntries = (Object.entries(worldOutsideLedgerEntryByEpoch) as Array<
  [keyof typeof worldOutsideLedgerEntryByEpoch, WorldOutsideLedgerEntryId]
>).map(([epochId, id], index) => {
  const fragments = fragmentsByEra[index + 1];
  if (fragments?.length !== 5) throw new Error(`World Outside Era ${index + 1} must contain five fragments`);
  return {
    id,
    epochId,
    name: `The World Outside, Era ${index + 1}`,
    category: 'The Eras',
    unlockSignal: index === 0 ? 'first-victory' : `epoch-activated:${epochId}`,
    hiddenUntilDiscovered: true,
    spriteRef: { slot: `world-outside.era-${index + 1}`, imageUrl: pageUrl },
    factLines: () => fragments.slice(0, 4),
    loreLine: fragments[4],
  } as const;
});
