name = "gold-rush"
pages_build_output_dir = "dist"
compatibility_date = "2026-07-08"

[[durable_objects.bindings]]
name = "MULTIPLAYER_ROOMS"
class_name = "MultiplayerRoom"
script_name = "gold-rush-mp-room"
