// s1619 handoff: rewrite STATUS.md line-1 and archive the s1619 lock line as a bullet.
// File-based (not `node -e`) because the text contains backticks the fire shell reads as a subshell.
import { readFileSync, writeFileSync } from 'node:fs';

const p = 'STATUS.md';
const text = readFileSync(p, 'utf8');
const nl = text.indexOf('\n');
const lock = text.slice(0, nl);
const rest = text.slice(nl + 1);
if (!lock.startsWith('ACTIVE 2026-08-10T07:35Z (s1619 fire)')) {
  console.error('LINE 1 IS NOT MY LOCK:', lock.slice(0, 90));
  process.exit(2);
}

const handoff = [
  'Last updated: 2026-08-10T07:56Z s1619 handoff, lock CLEARED — ',
  '🎯 **THE BOARD WAS DRY AND THE CANDIDATE LIST I INHERITED WAS 6/6 ALREADY SHIPPED, SO REFILLING IT WOULD HAVE BEEN MISTAKE #8 SIX TIMES OVER. I AUTHORED TWO MASTERS INSTEAD AND DISPATCHED BOTH; THREE LANES ARE NOW WORKING.** ',
  '📋 **BOARD ON ARRIVAL (07:33):** lock CLEARED (s1618, owning commit `88726e08d` — judged by the COMMIT per §1.1, never by stamp text) · **all six queues EMPTY** · lanes a/c/d `ahead=0` USABLE, **lane-b BUSY** — an attended Cowork session committed `ac87deb31` (minds-and-rigs fan pages) **35 seconds before I started** and its runner claimed the slot at 07:33:17 · no `tasks/CODEX-WALL` · assayer `pending/` **0** · ART untouched, no staging audit owed · **zero drainable output** (the one unprefixed done-move was residue, see HYGIENE). ',
  '🔎 **[F-1619-1] THE FINDING THAT DECIDED THE WHOLE FIRE — s1618 handed forward "the expensive half: a swept candidate list" of never-ran masters "with a LIVE first line", and ALL SIX ARE ALREADY ON MAIN.** `lane-a-perf-05-startup-attribution` (drained `63161278` s1039) · `lane-c-ed-04-gizmo-guards-vacuous` shipped · `lane-resource-timing-false-greens` merged · `lane-m2-01-fixture-coordinate` merged · `lane-d-rf-03b-specs-supersession` merged · `lane-b-asset-diet-budget-runnable` shipped. ',
  '✓ **Two of the six were verified by FILE PROBE, not by their leaves** (VERIFY-DON’T-INHERIT): perf-05’s `hasAny` needle now reads `/icon-` **with** the leading slash — precisely the cure that master proposed, so the `favicon-32.png` substring collision it was written to fix cannot occur; and `package.json` carries `test:asset-diet` running `e2e/asset-diet.spec.ts` under the preview config, which is the runnable budget check the asset-diet master was written to create. ',
  '⚠️ **THE REUSABLE HALF: the absence of a ⛔ DO-NOT-QUEUE header is SILENCE, NOT A NEGATIVE.** That header is hand-added, only when someone happens to notice a shipped master — so it marks a biased sample and is missing from everything nobody has looked at. **Sweeping on it selects for un-audited masters and calls them available**, which is Mistake #8’s exact intake path. ',
  '💡 **The check costs one second and already exists: `node scripts/drain-block-check.mjs <master>` prints `status="shipped"`/`"merged"` from the goal leaf** — ⚠️ **but READ THE WORD, NEVER THE TICK: it exits `0` with a green `✅ CLEAR` for a shipped leaf**, because its job is block-checking, not shipped-ness. A fire branching on the exit code alone reads *already merged* as *cleared for dispatch* — F-1262-3’s lesson recurring on a different field of the same tool’s output. ➡️ **A candidate list is worth handing forward only if each item was resolved by leaf + one file probe; a list swept on header-absence should be labelled UNAUDITED, not CANDIDATE.** ⓘ **Stated in s1618’s favour: that handoff was honest, flagged the list as "worth a stale-check, NOT a blind queue", and its ⭐ pick was chosen for the right reason — a live thread pointed at it. That thread is real and `f1619-2` now takes it up.** ',
  '🆕 **AUTHORED 2 (the cap, per the owner’s 2026-08-09 dry-board ruling; the board was DRY and ≥2 lanes were idle).** ',
  '**① `f1619-1-advance-stream-cache-reuse` → lane-c, QUEUED AND NOW RUNNING (claimed 07:44:35).** It is the probe **F-1616-3** prescribes verbatim — *walk the same five doors with NO `page.route` at all and count requests per URL* — and its GATE explicitly reads *"none owed to the owner; any fire may take the probe (one per fire)"*, so the allowance is now SPENT for s1619. ⭐ **If the WARM re-request is real rather than an interception artifact, the advance stream downloads its assets TWICE in normal play** — larger than any of the four slices that surfaced it. **Three design decisions, each earned from a prior finding:** (1) **CDP, not Playwright `request` events** — a cache-served resource may not surface as a `request` event and never reports whether bytes crossed the wire, so counting events yields a number that *looks* like an answer; the verdict is keyed on `Network.loadingFinished`’s `encodedDataLength`. (2) **The confound is separated from the finding** — removing `page.route` also removes the 150 ms throttle, so a demand fetch may now start while its prefetch is still in flight; that is a RACE, not a cache failure, so the master requires three buckets (**DOUBLE-DOWNLOAD** only when the prefetch reached `loadingFinished` *strictly before* the demand started and the demand still crossed the wire · **OVERLAP** · **CACHE-HIT**). (3) ⚠️ **It asserts NEITHER direction of the unknown** — only errors-empty plus two anti-vacuity assertions, the F-1616-1 lesson with the sign flipped. **A spec that asserts the unknown is a coin flip wearing a green tick.** ',
  '**② `f1619-2-asset-diet-town-budget-ab` → lane-a, QUEUED.** Settles the **~1.9 MB mobile asset-diet growth** unverified since f1615-1: the review records desktop `21,389,200 → 16,209,181` but mobile `15,181,572 → 17,074,995` — **opposite signs in two projects from one prefetch-set edit, and nobody has yet looked at WHICH URLs differ.** s1618’s deployed-bundle figures cannot settle it (different metric), and `f1617-1` narrows only the metered path, so main today still carries f1615-1’s number. ⭐ **The control is FREE, which is why this is one small task: because f1617-1 excludes the two bulk halls under `saveData`, a saveData arm IS a without-the-halls control** — an `addInitScript`, no code revert, no second checkout, nothing left uncommitted. ⚠️ **Its limit is stated rather than oversold** (`saveDataEnabled` also narrows to `priority === 1`), which is exactly why the master demands a **per-URL breakdown** instead of a delta number that would only invite a story. 🔒 **Gate topology deliberately UNCHANGED (the s1301 lesson): the test is ADDED to `e2e/asset-diet.spec.ts`**, already skip-guarded and already reached by `npm run test:asset-diet`; a new file would need a script, a `claimedByAnotherConfig` entry, and would silently join the default gate too. **Additions only, proved by `git diff --numstat` deletions reading `0`.** ',
  '⚠️ **[F-1619-2] MY OWN CITATION KEY WAS WRONG AND THE LANE CAUGHT IT — F-1425-2 working exactly as designed.** `f1619-1`’s READ-FIRST told the runner to find F-1616-3 by grepping `the WARM column measures request` in `tasks/BACKLOG.md`. It returns **0 there**: the ledger carries that sentence in **UPPERCASE** and the lowercase form lives in `reviews/advance-stream-walkthrough-drain.md`. I had proved three keys `=1` and eyeballed the fourth. Re-keyed to `Distinguishing them costs one probe` (`=1` in BACKLOG), re-committed, lane re-refreshed, **all four then proved `=1` inside the lane before the `cp`**. 💡 *A key copied from the file you meant is not a key proved against the file you named.* ',
  '📮 **DISPATCH ORDER PER F-1424-3, both masters:** master + leaf + BACKLOG row committed FIRST · lane refreshed SECOND (lane-c `behind=17 → 0`, lane-a `behind=9 → 0`) · citation keys re-proved `=1` **in the lane** THIRD · `cp` FOURTH, byte-identity confirmed by sha256 (`940c45c017bee1e4`, `6e2a0dbafe592d3a`). Both leaves registered in the SAME commit as their master (Goal Registration Law); `tasks/goals.json` edited **surgically — 9 insertions / 0 deletions each**, by raw-text splice with a `JSON.parse` round-trip check, per s1618’s tooling note. ',
  '📮 **STANDING DUTIES:** **TK-01 — nothing owed**: the 2026-08-09 digest was filed by s1618 at `marketing/outbox/ticker-digest-2026-08-09.md` and it was the first fire after 06:00 today · **GZ-01 — nothing owed, and checked rather than assumed**: `git log --merges` since 06:00 returns exactly one merge, `f5dbb5448`, and `grep -rl f5dbb544 marketing/outbox/` finds it already carried (the F-1600-1 short-hash-across-the-whole-outbox form). Everything else since s1618 is authoring commits, which are not player-visible · assayer `pending/` **0** · **ART untouched — no staging audit owed** · **DEPLOY correctly SKIPPED: this fire merged nothing** (two authored masters and ledger rows; bookkeeping-only fires skip deploy) · backup push at handoff. ',
  '🧹 **HYGIENE:** the one unprefixed done-move was **residue, not work** — `drain-block-check` reports f1615-1’s leaf `status="merged"`, matching s1618’s re-land, so it is now prefixed `drained-f5dbb5448-BY-RE-LAND-`. ⚠️ **The two untracked masters `tasks/lane-agent-reels-emitter.md` / `lane-agentreel1-door-tape.md` were left UNTOUCHED for the third fire running, and the reason is now written down so nobody keeps re-deciding it:** they are superseded 04:55/04:59 drafts of `tasks/lane-agent-reels.md`, whose thread is **owner-blocked at F-1617-1**, and they belong to a **live attended session** — committing another writer’s in-flight files is the F-1295-1 custody hazard with the roles reversed. **They are 2 KB, they are not the F-1501-3 problem, and the next fire should leave them too unless the attended session asks otherwise.** No gate worktrees and no dev servers were needed this fire (nothing to gate). ',
  '🏜️ **PIPELINE:** lanes **b (minds-and-rigs, attended-queued)**, **c (f1619-1)** and **a (f1619-2)** are all working; **lane-d is idle and I did not fill it** — my authoring cap was spent, its natural next work (`agent-reels`) is the desked F-1617-1 fork, and every stale master I checked was shipped. **PIPELINE-DRY: lane-d (needs spec/owner).** ',
  '🔭 **NEXT FIRE (A) DRAIN `f1619-1` from lane-c when it finishes — it is the biggest open lead on the board** and its answer decides whether a much larger performance slice exists. Read the DOUBLE-DOWNLOAD bucket, not the raw re-request count; the master separates the race confound on purpose. **(B)** drain `f1619-2` from lane-a — the per-URL table is the deliverable, not the totals. **(C)** `minds-and-rigs` on lane-b is attended-authored and will need draining like any other lane output. **(D)** lane-d wants either a spec slice or the F-1617-1 ruling. **(E)** the f1615-1 runner’s explicitly UNVERIFIED `240/246` `--repeat-each=3` and `22/28` adjacent tallies are still unconfirmed drain-side; **F-1618-2 says do not try to settle them in a fire shell.** ',
  '🔺 **OWNER’S DESK — 14 awaiting a word.** ⓵ `desk-state-audit --status` against s1618’s archived line-1: **`CLOSED=0 · OPEN=0 · BOTH=0 · OPEN-DESK-ONLY=14 · UNRECORDED=0`** — nothing carried should have been dropped and no carried item is a ghost. **Both of my findings (F-1619-1, F-1619-2) say GATE: none owed to the owner** — one is a measurement about sweeping, the other a lesson for fires. ',
  '🔺 **F-1617-1 OPEN** — the tape format cannot represent an agent run; you already ruled *emit+backfill*, what is open is only the REPRESENTATION: **(a)** a bounded `agent_orders` tape action taught to the reel player (**REC**) or **(b)** a separate standing-order log ',
  '🔺 **F-DOOR-6 OPEN** — only **(c)**, publishing build zones in the map block, is yours ',
  '🔺 **F-1608-2 OPEN** — the Trestle/Incline railcars are byte-identical to the Hill Mine one just tuned; *"probably the same"* is not a ruling ',
  '🔺 **F-1193-3 OPEN** — fourth premise spent and failed; **(a)** retire the diagonal ambition (REC) or **(b)** fund a premise changing the FIGURE-SIDE instruction ',
  '🔺 **F-1501-3 OPEN** — 582 files / 527.89 MB in no object database ',
  '🔺 **F-1601-1 OPEN** — the `gateClass` column needs an attended nod ',
  '🔺 **F-1510-1 OPEN** — mechanical gate MET s1609; *keep the go-around* (REC) or *the complaint moved* ',
  '🔺 **F-E2S-3 OPEN** — socket half needs its census-stream slice specced ',
  '🔺 **F-1536-2 OPEN** — census done; renames + dynamic panel need a word ',
  '🔺 **F-1591-1 OPEN** — Arm 0’s gate MET, clamp unconfirmed below the knee; F-1593-2 counsels parking ',
  '🔺 **F-1507-1 OPEN** — both shells on one node version ',
  '🔺 **F-E2S-4 OPEN** — genuinely owner-gated ',
  '🔺 **F-1101-1 OPEN** — parked KNOWN-INCOMPLETE by your ruling ',
  '🔺 **F-1166-1 OPEN** — awaiting your word since s1166.',
].join('');

const archive = '- **s1619 lock line (archived):** ' + lock;
writeFileSync(p, handoff + '\n' + archive + '\n' + rest);
console.log('handoff written,', handoff.length, 'chars');
