import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const p = path.join(ROOT, 'STATUS.md');

const prevLine1 = fs.readFileSync('/tmp/s1448-line1.txt', 'utf8').trim();

const line1 = [
  'Last updated: 2026-08-04T04:05Z s1449 handoff, lock CLEARED — ✅ **ONE DRAIN, SHIPPED: THE DRILL-YARD PROPS ARE ON THE PLAYER\'S SCREEN AFTER TWO FIRES DORMANT — AND THE DRAIN CAUGHT A DEFECT THAT WOULD HAVE SHIPPED, IN EVERY KEYED SPRITE IN THE GAME.**',
  '🔎 **(A) `art-drill-yard-props-extracted` MERGED `a7b7eddb596c884421e9ba43096f7b85abde7fcf`.** Review `reviews/art-drill-yard-props-extracted.md`; LEDGER row 70 closed; leaf `e1-drill-yard-stations-keyed` flipped `queued → merged`; BACKLOG F-BW-8 / F-1447-1 thread CLOSED. The wiring merged at `646e2d31` and had been **dormant ever since**: `applyStationArt` resolves through an eager `import.meta.glob` and **returns silently on a miss**, so three absent PNGs cost nothing at build time, nothing at runtime, and showed the player procedural placeholders (F-1437-3). One command fixed it — `--key ff00ff --size 384`, the size matched to the `prop-baron-banner.png` precedent (same slot, same generator, same native 1254×1254). Gated on **scratch port 5237, never 5188**, because lane-c ran `f1448-1` for the whole fire (Mistake #12): tsc clean · build **1.16 s** · new plain-boot `e2e/drill-yard-station-art.spec.ts` **2/2** desktop + 390px, zero console errors · adjacent **derived by grep** (`drill-yard`, `drill-yard-manifest`, `cp01-charter-roundtrip`) **28/28** both projects · `gr-sim` **9/9** · node guards **36/36** · `test:ledger-guards` green as the LAST act, after the bookkeeping commit (F-1300-4) — 42 node tests + 6 standalone + **both shell guards run through `node` because the bash allowlist refuses the form, not the factory**.',
  '⭐ **THE GREEN MEANS SOMETHING BECAUSE THE RED WAS MANUFACTURED:** with the three PNGs moved out and nothing else changed, the spec goes **RED** with `stationArt` reading `Array []` — the exact dormant state — then restored byte-identical. That also answers the *"would notice a rename"* clause of the stated gate, since **a rename and an absence are the same event to a glob**. The new `DrillYardDiagnostics.stationArt` is what makes any of it visible: **this defect class hid for two fires precisely because nothing could see it.**',
  '🔺 **(B) F-1449-1 — FOUND AT THIS DRAIN, FIXED AS A CLASS (`d2e69801`), AND IT AFFECTS EVERY KEYED SPRITE, NOT JUST THIS BATCH.** The first extraction was correct by **every number the probe had** — corners `alpha=0`, transparent fraction matching each raw\'s own `#ff00ff` fraction to a tenth of a percent, **residual magenta 0** — and drew a **bright magenta halo around every prop in game**. Keying sets alpha 0 but **leaves the key colour in RGB**, and *the GPU does not consult alpha when it filters*: bilinear filtering and mipmaps average RGB across neighbouring texels, so `#ff00ff` under the transparency bleeds into every edge texel surviving `alphaTest` — worst on **thin features** (table legs, bell frame posts), where downscaling averages one real texel against several key texels. Measured: **100% of transparent pixels held key-magenta RGB**, including **3,982 / 1,540 / 1,755** directly touching visible art. **The already-shipped `prop-baron-banner.png` carries the identical property (4,128) — so the fault is `extract-alpha.mjs`, not the batch.** `bleedEdges()` propagates visible colour outward under the transparency to exhaustion and **never touches alpha**: transparent/opaque/partial counts and subject bboxes are **identical before and after**, so the cut-out is bit-for-bit the same shape, and key-magenta under transparency goes **100% → 0%**. `despillSaturatedKey` could never have caught it — it skips transparent pixels *by design*, because it corrects spill **on** the art, not **under** it.',
  '⭐⭐ **THE REUSABLE LESSON, AND THE ONLY REASON THIS WAS CAUGHT: THE PROBE WAS NOT WRONG — ITS QUESTION WAS.** It asked whether magenta survived among the **visible** pixels and truthfully answered 0. A number can be precise, correct, and about the wrong pixels. **Looking is what caught it** (F-1446-1) — and this is now the THIRD consecutive drain on this one batch decided by an eye rather than a table (s1445 gallows, s1446 retake, s1449 halo). Before/after: `artifacts/drill-yard-props/zoom-assay-table{,-fixed}.png`.',
  '🟡 **F-1449-2 — LEDGER row 70 TRANSPOSED TWO OF ITS OWN MEASUREMENTS; CORRECTED THERE BY THIS DRAIN.** It recorded the `#ff00ff` counts as `949,360 / 1,222,187 / 1,174,778 px (60.37% / 77.72% / 74.71%)` in the file order faucet · bell-post · straw. Re-derived from the raws: bell-post is **1,174,778 (74.71%)** and straw **1,222,187 (77.72%)** — **swapped**. Every number was real; two were attached to the wrong filenames, and a future retake QA\'d against the row would have been measured against its sibling\'s baseline.',
  '🟡 **F-1449-3 OPEN — ⭐ THE CHEAPEST WIN ON THE BOARD AND THE OBVIOUS NEXT-FIRE PICK: `prop-baron-banner.png` STILL SHIPS WITH THE F-1449-1 HALO.** The cure now exists and re-extraction is **one command**. Deliberately NOT done here: it is a different asset on a different surface and deserves its own before/after in-game QA rather than a drive-by. ⚠️ **Check its extraction flags before re-running — do not assume `--size 384` alone; read how it was originally produced.** 🟢 **F-1449-4** — a glob miss is now *observable* via `stationArt` but still not *loud*; left deliberately, since a hard failure would red every headless harness that legitimately lacks processed art.',
  '🚀 **(C) NEXT FIRE, HIGHEST PRIORITY — `f1448-1` LANDED WHILE I WORKED AND IS UNDRAINED. THE F-1448-1 BLOCKER IS CURED AND `f1441-2` CAN FINALLY MERGE.** Done-move `20260804-030748-f1448-1-crossings-keep-the-hero-out-of-it.md` (un-prefixed); `drain-block-check` answers **✅ CLEAR** on it (exact leaf match, `status: "planned"`). **lane-c `lane/e2-arsenal` is ahead=2, behind=26, tracked-dirt=0, untracked=0** — tip **`4e2d9d0e`** (the cure) over **`a26454d4`** (f1441-2), so **merging the lane tip brings BOTH**. The runner **CONFIRMED F-1448-2** — the module-scope `Terrain` init was indeed the only path in the diff that could reach the hero — and cured it by deferring behind a cached `crossingData()` (`Enemy.ts:1446`). **Its matched battery reads exactly as the master demanded, by NAME and not "fewer reds": eager lane 9 · clean main 8 · lazy cure 8, with `gt-05:181` GREEN on both projects**; `deepSamples === 0` both projects; `never-trap` 8/8; `twin-banks-never-wedged` 2/2; `gr-sim` 9/9 with all three pins **unchanged** (`80c5cae4`, kills `202`, `5aeceb84`); tsc + build green; zero console errors at 1280×800 and 390×844; shots at `reviews/shots-f1448-1`. ⚠️ **RE-DERIVE, DO NOT INHERIT — that report is a claim, and this exact slice is the one where the red inventory would have exonerated the wrong thing (F-1444-2, F-1448-1).** Gate the MERGED tree yourself under a matched control. ⓘ It also reports a later unrelated Dry Gulch GLTF blob-texture red that its preserved eager control reproduced identically — environmental, but **verify that rather than accept it**. 📌 **The f1441-2 leaf is `blocked` + `blockClass: gate-side`, so NO OWNER OWES A WORD — a fire lifts it with evidence; and the f1441-2 gate is ALREADY BANKED in `reviews/f1441-2-crossings-keep-their-z.md`, so do NOT re-gate it from scratch.** Land it as **TWO COMMITS IN ONE FIRE — code commit, then leaf commit** (F-1384-1: a commit cannot contain its own hash).',
  '📋 **(D) BOARD, MEASURED THIS FIRE WITH `lane-usable --all`, NOT INHERITED: lane-a HOLDS** (ahead=5, behind=144 — 1 real line of `e2e/drill-yard-spec` + 2 binaries; archive-first cure available) · **lane-b HOLDS and stays DO-NOT-QUEUE** (`disputed` leaf, ahead=7, behind=779) · **lane-c HOLDS** = the drain above · **lane-d USABLE, ahead=0, tracked-dirt=0, queue EMPTY.** 🔻 **A lane-d refill is owed for the THIRD consecutive fire and I again did not take it — stated plainly rather than buried:** my time went to the drain and to F-1449-1, and picking a ladder item unread at the end of a fire is exactly Mistake #8. **This is now a pattern, not a coincidence, and the next fire should either refill lane-d or say why in the same words.** The genuinely cheap owed work I *can* name without inventing scope is **F-1449-3** — but that is fire-side art, not a lane task.',
  '📰 **GZ-01: item APPENDED** to `marketing/outbox/gazette-queue.md` — this fire merged a real player-visible change, so one was owed ("The county sets out its tools at the training ground", NO OWNER CHOICE). ⏰ **TK-01: the 2026-08-03 digest is NOT yet due, and here is the evidence rather than a silent deferral** — it belongs to the first fire after **06:00 local** on 08-04, and this handoff is **04:05**. **Do not write it early; do not defer it silently past 06:00.** Assayer `pending/` **empty**. 🎨 **ART: not touched, so no staging audit was owed and none is claimed** — the standing `staging/motion-pilot` hole (582 files / 527.89 MB AT RISK) is unchanged because I added nothing to it.',
  '🔍 **RETENTION: every instrument is committed under `artifacts/drill-yard-props/`** — `probe-cutout.mjs`, `probe-fringe.mjs`, `crop-zoom.mjs`, `build-board.mjs`, `run-gate.mjs`, `run-sh-guards.mjs`. Not a summary of the numbers: the tools that produced them, so every figure above is re-derivable.',
  '**ROBIN OWES (unchanged, nagged politely, never blocking): lane-d attempt-3 verdict · turret-feel + water-feel playtests · Mac full-regression evidence · favicon 16px eyeball.** 🙏 **RUNNER RESTART, FIFTEENTH fire — and this fire is again evidence for BOTH halves:** pid 35584 claimed `f1448-1` within a minute and ran it to completion, so it demonstrably works; the ask remains only that it is up 23 days with seven shipped cures inert inside it.',
  '👁️ `artifacts/drill-yard-props/comparison-board.png` (NEW — the three props on a checkerboard) · `artifacts/lane-night-visibility/comparison-board.png` · 🌊 `artifacts/tb-water-look/compare/` · 🏰 palisade kit playtest · `artifacts/baron-props/comparison/desktop-props-and-flight.png` (F-1443-3) · `artifacts/mill-horizon-copy/`. ⭐⭐ **F-1396-4** · ⭐⭐ **CLOSE LAUNCH (`rf-05-fixed-version`)** · ⭐⭐ **THE 27-MAP CAMPAIGN, waiting since 2026-07-18** · ⭐ **AP-03 RE-GREENLIGHT** · 💵 the 2026-07-11 pose-library run: **108 credits or 324?** · 🟢 **F-1330-1** (115th carry, rec **(a)**).',
  '🚫 **NEW STANDING: do NOT re-extract any keyed sprite with a pre-`d2e69801` checkout** — you would silently reintroduce the F-1449-1 halo. 🚫 **do NOT "simplify" `bleedEdges()` to a fixed few-pixel skirt** — mip level N averages 2^N texels, which is why it fills to exhaustion. 🚫 **do NOT read a numeric cut-out probe as proof a sprite is clean — LOOK at it in game (F-1449-1).** 🚫 do NOT rename the three `assets/processed/prop-drill-*.png` files — the glob is eager and by exact name (F-1437-3). **CARRIED FORWARD:** 🚫 do NOT read `red-inventory-lookup`\'s KNOWN-RED as exoneration (F-1444-2) · 🚫 do not "cure" F-1448-1 by editing `e2e/gt-05-water-depth.spec.ts`, which is the JUDGE · 🚫 do not re-pin a `gr-sim` hash to make a red go away (F-1441-3) · 🚫 do not reset or `git clean` lane-c (archive ref `archive/lane-e2-arsenal-s1448-5c27a1b5-held-f1448-1`) · 🚫 `lane-drill-yard-affordances` IS SHIPPED (`646e2d31`) · 🚫 do NOT extract the drill-yard props with `--full-bleed` · 🚫 do not restore the archive\'s `blockerSlideDirection` from `9236e9ba` (F-1446-3) · 🚫 `054-baron-epic.spec.ts:312` is a load flake — no merge withheld on it without a MATCHED control · 🚫 `PORT` does NOT set the playwright port — use `GR_CAPTURE_BASE_URL` (F-1443-4) · 🚫 do not gate `release-build.spec.ts` by adding it to the default config (F-1296-3) · 🚫 do not "fix" the boss bar back to the object frame — owner ruling · 🚫 do not read a FILTERED playwright report when a red decides a merge (F-1442-1) · 🚫 do not merge `9236e9ba` as-is · 🚫 do not land `e2e/e1-perf-pass.spec.ts` unchanged (F-1440-2) · 🚫 do not re-drain `183562b3` / `bec2b387` / `452eb747` / `4d4fc858` / `a0412139` / `90f938ad` / `4070ace5` · 🚫 do not "cure" F-1439-1 by deleting `run-suspend`\'s console-error assertion · 🚫 do not author the fort-solidity successor until `Enemy.ts` is settled (F-1439-5) — **note `Enemy.ts` is STILL unsettled until (C) lands** · 🚫 do not write a master telling a runner to reuse another LANE\'s output (F-1439-4) · 🚫 do not merge `lane/m4` at branch level · 🚫 do not gate on 5188 while a lane is live · 🚫 do not "cure" F-1438-1 by raising the 1.15 ratio · 🚫 do not kill pid 35584 yourself · 🚫 do not carry a `gate-side` leaf to the owner\'s desk · 🚫 do not queue into lane-b until the `disputed` leaf is ruled · 🚫 do not hand-reset lane-a without archiving first · 🚫 **DO NOT reset lane-b (F-1421-1)** · 🚫 do not re-queue `f1424-4` unchanged (F-1426-1) · 🚫 do not add `fullyParallel` to `playwright.config.ts` · 🚫 do not pin `workers` unconditionally · 🚫 do not widen `CHURN` in `lane-usable.mjs` (F-1212-4) · 🚫 do not change `RICH = 8` in `lane-residue.mjs` (F-1419-1) · 🚫 **do not touch the retention epitaph** · 🚫 **do NOT prune `test:ledger-guards`** · 🚫 DO NOT fix cp03 (F-1396-2) without the owner word · 🚫 do not commit the 949 MB archive raw (F-1436-4) · 🚫 do not delete or gitignore `logs/factory-usage.json` / `logs/usage-history.jsonl`.',
  '✅ **F-1449-1 FIXED `d2e69801`** · ✅ **F-1449-2 CORRECTED** · 🟡 **F-1449-3 OPEN (cheapest win)** · 🟢 F-1449-4 · 🔺 **F-1448-1 CURED IN LANE, UNDRAINED — see (C)** · ✅ F-1448-2 CONFIRMED by the runner · 🟢 F-1448-3 · 🟢 F-1448-4 · 🟢 F-1448-5 · 🟡 **F-1448-6** (goal-leaf debt, 14th consecutive fire — **526 of 762 masters with no leaf; every leaf I touched was correct, and F-1443-1\'s ask STANDS: should authoring hard-STOP without a leaf?**) · 🔺 **F-1441-2 GATED, HELD, STILL NOT MERGED — its blocker is now cured** · ✅ F-1441-3 PAID · 🔺 **F-1443-3 OPEN** · 🔺 **F-BW-14 STILL OPEN** · 🟢 F-1447-2 · 🟢 F-1445-2 · 🟡 F-1445-3 · 🔺 F-1440-2 · 🟡 F-1440-4 · 🟡 F-1439-1 · 🔺 F-1439-4 · 🔺 F-1439-5 · 🟡 F-1438-1 · ✅ **F-1437-3 CLOSED by (A)** · 🟡 F-1436-4 · 🟡 F-1433-2 · 🟢 F-1433-4.',
].join(' ');

const lines = fs.readFileSync(p, 'utf8').split('\n');
lines[0] = line1;
lines.splice(1, 0, `- **s1448 handoff (line-1 archive):** ${prevLine1}`);
fs.writeFileSync(p, lines.join('\n'), 'utf8');

console.log('line-1 length:', line1.length);
console.log('archived s1448 handoff line-1, length:', prevLine1.length);
console.log('line2 now:', lines[1].slice(0, 90));
console.log('line3 now:', lines[2].slice(0, 90));
