// The twelve rows of the needs-cells batch. One entry = one strip of uniform cells.
// STYLE ANCHOR is specs/epoch-saga/e2-steamworks-bundle.md:6-8, verbatim, in every prompt.
export const ANCHOR = 'Frontier Ledger style: hand-engraved storybook illustration, fine ink hatching and cross-hatch shading, parchment-warm palette of ochres, sepias and warm browns with restrained teal agent-tech glow accents; illustrated and warmly readable, never photorealistic, never gory, no text or letters or watermarks anywhere in the image.';

const sheet8 = 'THE PICTURE: one single flat pure magenta #ff00ff field fills the whole image from edge to edge. Standing on that magenta field are EXACTLY EIGHT separate full-length drawings of the same character, all exactly the same size: EXACTLY FOUR spread evenly across the upper half of the image and EXACTLY FOUR spread evenly across the lower half, eight in total, never seven and never nine. Taken left to right along the top and then left to right along the bottom they are walk-cycle phases 1 to 8 of one continuous loop.';
const sheet4 = 'THE PICTURE: one single flat pure magenta #ff00ff field fills the whole image from edge to edge. Standing on that magenta field are EXACTLY FOUR separate full-length drawings of the same character, all exactly the same size: EXACTLY TWO spread evenly across the upper half of the image and EXACTLY TWO spread evenly across the lower half, four in total, never three and never five. Taken left to right along the top and then left to right along the bottom they are walk-cycle phases 1 to 4 of one continuous loop.';

export const RENDER = 'THIS IS A CONTINUATION OF AN EXISTING SPRITE SHEET. The new cells must be INDISTINGUISHABLE from the attached reference cells in technique, palette, value range and level of detail — as if painted by the same hand in the same sitting. Technique: soft painterly ink-and-wash over a light graphite underdrawing, fine cross-hatching for shadow, thin and varied line weight, contours that melt into the shading, muted low-saturation dusty pigment, warm sepia key light. STRICTLY FORBIDDEN: thick uniform black outlines of any kind, dark keylines around the silhouette, flat cel-shaded blocks of colour, saturated comic-book colour, poster or vector-icon rendering, sticker edges, cartoon proportions.';

export const SHEET_LAW = 'The magenta field is completely empty apart from those figures: nothing is drawn on it, over it or around it, and it is the same flat pure magenta everywhere, right into the corners. Each figure is drawn independently — never a mirrored, flipped or copied version of another — and every one of them is the same character at the same size with the same costume and colours. Each figure stands well inside the picture with a generous band of empty magenta above the head, below the feet and on both sides, and the feet of every figure sit at the same height as each other. No text, letters, numerals, signature or watermark anywhere. No firearms. No blood.';

const phases8 = 'The eight drawings are eight clearly DIFFERENT moments of one stride and no two of them repeat: (1) LEFT CONTACT - the legs at their widest, left heel just landed, right toe still down; (2) DOWN - legs closing under the body, the body at its lowest; (3) PASSING - the right leg swings through with the knee lifted, the feet almost together; (4) UP - the body at its highest, pushing off the right toe, the left leg reaching; (5) RIGHT CONTACT - the mirror moment of (1), right heel just landed; (6) DOWN again; (7) PASSING with the left leg swinging through; (8) UP again. The stride is wide in 1 and 5 and narrow in 3 and 7, and the head rises and falls with it. Arms swing in counter-time to the legs. EVERY figure is seen from EXACTLY the same camera angle and the same distance; nothing about the viewing angle, the body, the costume, the colour, the size or the drawing style changes between them — only the walking pose. This is NOT a turnaround and NOT a character sheet of different views.';
const phases4 = 'The four drawings are four clearly DIFFERENT moments of one stride and no two of them repeat: (1) CONTACT - the legs at their widest, the leading heel just landed and the trailing toe still down; (2) DOWN - the legs close together under the body, the body at its lowest, the back foot lifting; (3) PASSING - the back leg swings through with the knee bent and lifted, the feet almost together; (4) UP - the body at its highest, pushing off the back toe, the leading leg reaching forward. The stride is wide in 1 and narrow in 3, and the head rises and falls with it. Arms swing in counter-time to the legs. EVERY figure is seen from EXACTLY the same camera angle and the same distance; nothing about the viewing angle, the body, the costume, the colour, the size or the drawing style changes between them — only the walking pose. This is NOT a turnaround and NOT a character sheet of different views.';

const BARON = 'The character is the SAME man as in the reference image, the Claim-Jumper Baron: a stout, heavy-set frontier magnate in a tall black top hat with a white playing card tucked into the hatband, a broad silver-grey handlebar moustache and grey side-hair on a ruddy face, a long deep oxblood-red frock coat with brass buttons and turned-back cuffs, a tan-gold buttoned waistcoat with a watch chain, grey pin-striped trousers and brown leather boots. Keep his costume, palette, proportions, line weight and ink-hatched shading exactly as the reference.';
const JUMPER = 'The character is the SAME figure as in the reference image, the Claim Jumper: a wiry crouching frontier outlaw in a flat-brimmed straw hat, a ragged rust-red woollen poncho or kerchief over the shoulders, a tan canvas shirt and dusty ochre canvas trousers with a small satchel at the hip, worn boots and wrapped forearms, hunched low in a prowling walk. Keep his costume, palette, proportions, line weight and ink-hatched shading exactly as the reference.';
const WRECKER = 'The subject is the SAME machine as in the reference image, the Steam Wrecker: a squat brass spider-boiler on four short jointed brass legs with bell-shaped feet, a riveted spherical boiler body, two slim chimneys venting soft white steam, one round amber-glowing porthole eye on its FRONT face only, one small teal-glass gauge panel on its body-LEFT flank, and two curled open-jawed wrench arms reaching forward. Keep its build, palette, brass tone, line weight and ink-hatched shading exactly as the reference.';
const THIEF = 'The character is the SAME man as in the reference image, the Coal Thief: a lean frontier man in a wide flat-brimmed tan hat and a blue-grey bandana pulled over his nose, a ragged grey-brown coat over a pale shirt with rolled sleeves, dark brown trousers and heavy boots, hauling one big lumpy sack heaped with black coal slung over his BODY-RIGHT shoulder so the sack always trails BEHIND his direction of travel. Keep his costume, palette, proportions, line weight and ink-hatched shading exactly as the reference.';
const TEACHER = 'The character is the SAME woman as in the reference image, the frontier schoolteacher: dark curly hair pinned up in a loose bun, a cream white blouse with full gathered sleeves, a rust-brown buttoned waistcoat-bodice, a narrow sage-green ribbon tied at the throat, a long olive-brown tiered skirt with a ruffled hem, a small brown leather satchel on a strap at her hip, and brown ankle boots. Keep her costume, palette, proportions, line weight and soft painterly shading exactly as the reference.';

const P = 'assets/processed/';
const D = '/tmp/diag/';
export const ROWS = [
  { id: 'baron-e', family: 'baron', grid: '4x2', frames: 8, cell: 512, band: [379, 395], aim: 388,
    refs: [P+'char-baron-w-clean-v2-r0c0.png', P+'char-baron-w-clean-v2-r0c2.png', P+'char-baron-w-clean-v2-r1c0.png', P+'char-baron-sheet-walk8-r0c0.png'],
    subject: BARON, sheet: sheet8, phases: phases8,
    facing: 'In every cell he is seen in RIGHT-FACING SIDE PROFILE, walking east — his nose, chest, knees and boots all point to the RIGHT edge of the cell, his back to the LEFT edge. This is the true opposite-side view of the reference (which faces left); it is NOT a mirrored copy — the far arm, the coat lapel and the watch chain sit where the other side of his body really puts them. THE PLAYING CARD IN HIS HATBAND IS TUCKED ON HIS RIGHT, THE FAR SIDE FROM THIS CAMERA: it is hidden behind the crown of the hat and must NOT appear in any figure. All eight figures are identical in costume and in size — same coat, same waistcoat, same watch chain, same hat, no card on any of them.' },

  { id: 'jumper-n', family: 'jumper', grid: '2x2', frames: 4, cell: 256, band: [156, 174], aim: 165,
    refs: [P+'char-jumper-sheet-walk4-b-r0c0.png', P+'char-jumper-sheet-walk4-b-r0c1.png', P+'char-jumper-sheet-walk4-b-r0c2.png', P+'char-jumper-sheet-walk4-b-r0c3.png'],
    subject: JUMPER, sheet: sheet4, phases: phases4,
    facing: 'In every cell he is seen FROM DIRECTLY BEHIND, walking north, away from the viewer, into the depth of the picture: we see the back of his straw hat brim, the back of the rust-red poncho, his shoulder blades and the backs of both boots. No face, no eyes, no front of the poncho is visible.' },

  { id: 'jumper-w', family: 'jumper', grid: '2x2', frames: 4, cell: 256, band: [156, 174], aim: 165,
    refs: [P+'char-jumper-sheet-walk4-b-r2c0.png', P+'char-jumper-sheet-walk4-b-r2c1.png', P+'char-jumper-sheet-walk4-b-r2c2.png', P+'char-jumper-sheet-walk4-b-r2c3.png'],
    subject: JUMPER, sheet: sheet4, phases: phases4,
    facing: 'In every cell he is seen in LEFT-FACING SIDE PROFILE, walking west — his hat brim, chest, knees and boots all point to the LEFT edge of the cell, his back to the RIGHT edge, the rust-red poncho trailing behind him to the right.' },

  { id: 'wrecker-se', family: 'steamwrecker', grid: '2x2', frames: 4, cell: 512, band: [228, 252], aim: 244, mode: 'same',
    refs: [D+'char-steamwrecker-sheet-walkdiag4-a-r1c0.png', D+'char-steamwrecker-sheet-walkdiag4-a-r1c1.png', D+'char-steamwrecker-sheet-walkdiag4-a-r1c2.png', D+'char-steamwrecker-sheet-walkdiag4-a-r1c3.png'],
    subject: WRECKER, sheet: sheet4, phases: phases4,
    facing: 'The reference already shows the exact camera angle you must draw: the machine walking SOUTH-EAST, toward the viewer and toward the RIGHT edge of the picture. Keep that angle exactly in all four drawings. The amber porthole eye is LIT AND CLEARLY VISIBLE in every one of the four, the teal gauge panel sits on the left of the boiler, and one wrench arm reaches toward the lower right.' },
  { id: 'wrecker-sw', family: 'steamwrecker', grid: '2x2', frames: 4, cell: 512, band: [228, 252], aim: 244, mode: 'halfway',
    refs: [P+'char-steamwrecker-sheet-walk4-a-r0c0.png', P+'char-steamwrecker-sheet-walk4-a-r0c2.png', P+'char-steamwrecker-sheet-walk4-a-r1c0.png', P+'char-steamwrecker-sheet-walk4-a-r1c2.png'],
    subject: WRECKER, sheet: sheet4, phases: phases4,
    facing: 'The two references are the machine seen head-on from the south and the machine seen in left-facing profile from the west. Draw it exactly between them: walking SOUTH-WEST, toward the viewer and toward the LEFT edge, turned 45 degrees to the left of head-on. The amber porthole eye IS lit and visible, carried round to the left of the boiler rather than centred, and one wrench arm reaches toward the lower left, nearer the camera and larger than the other.' },
  { id: 'wrecker-ne', family: 'steamwrecker', grid: '2x2', frames: 4, cell: 512, band: [224, 244], aim: 234, mode: 'same',
    refs: [D+'char-steamwrecker-sheet-walkdiag4-a-r3c0.png', D+'char-steamwrecker-sheet-walkdiag4-a-r3c1.png', D+'char-steamwrecker-sheet-walkdiag4-a-r3c2.png', D+'char-steamwrecker-sheet-walkdiag4-a-r3c3.png'],
    subject: WRECKER, sheet: sheet4, phases: phases4,
    facing: 'The reference already shows the exact camera angle you must draw: the machine walking NORTH-EAST, away from the viewer and toward the RIGHT edge of the picture. Keep that angle exactly in all four drawings. The amber porthole eye is on the far side and is NOT VISIBLE IN ANY of the four — every drawing shows the riveted back of the boiler with no lit amber lamp anywhere — the teal gauge panel shows on the left, and one wrench arm reaches away to the upper right.' },
  { id: 'wrecker-nw', family: 'steamwrecker', grid: '2x2', frames: 4, cell: 512, band: [224, 244], aim: 234, mode: 'halfway',
    refs: [P+'char-steamwrecker-north4-v2-r0c0.png', P+'char-steamwrecker-north4-v2-r1c0.png', P+'char-steamwrecker-sheet-walk4-a-r1c0.png', P+'char-steamwrecker-sheet-walk4-a-r1c2.png'],
    subject: WRECKER, sheet: sheet4, phases: phases4,
    facing: 'The two references are the machine seen from directly behind walking north and the machine seen in left-facing profile from the west. Draw it exactly between them: walking NORTH-WEST, away from the viewer and toward the LEFT edge, turned 45 degrees. The amber porthole eye is on the far side and is NOT visible in any of the four drawings; we see the riveted back of the boiler swung to the right and one wrench arm reaching away to the upper left.' },

  { id: 'thief-se', family: 'coalthief', grid: '2x2', frames: 4, cell: 512, band: [246, 276], aim: 260, mode: 'halfway',
    refs: [P+'char-coalthief-sheet-walk4-a-r0c0.png', P+'char-coalthief-sheet-walk4-a-r0c2.png', P+'char-coalthief-sheet-walk4-a-r2c0.png', P+'char-coalthief-sheet-walk4-a-r2c2.png'],
    subject: THIEF, sheet: sheet4, phases: phases4,
    facing: 'The two references are the man seen head-on walking south toward the viewer and the man seen in right-facing profile walking east. Draw him exactly between them: walking SOUTH-EAST, toward the viewer and toward the RIGHT edge, his body turned 45 degrees so that his boots and the brim of his hat point to the lower right, his left shoulder nearer the camera than his right. His bandana and part of his face are still visible. The coal sack trails behind him, over his far shoulder, on the LEFT side of the drawing.' },
  { id: 'thief-sw', family: 'coalthief', grid: '2x2', frames: 4, cell: 512, band: [246, 276], aim: 260, mode: 'same',
    refs: [P+'char-coalthief-sheet-walk4-a-r1c0.png', P+'char-coalthief-sheet-walk4-a-r1c1.png', P+'char-coalthief-sheet-walk4-a-r1c2.png', P+'char-coalthief-sheet-walk4-a-r1c3.png'],
    subject: THIEF, sheet: sheet4, phases: phases4,
    facing: 'The reference shows him in flat left-facing profile. Turn him a little toward the viewer, a quarter turn, so that he walks toward the BOTTOM-LEFT CORNER of the picture: his boots and the brim of his hat still point LEFT in every one of the four drawings, never right, but now we also see a little of his chest and the front of the bandana. The coal sack stays exactly where the reference puts it, over his shoulder on the RIGHT side of the drawing, trailing behind him.' },
  { id: 'thief-ne', family: 'coalthief', grid: '2x2', frames: 4, cell: 512, band: [246, 276], aim: 258, mode: 'same',
    refs: [P+'char-coalthief-north4-v2-r0c0.png', P+'char-coalthief-north4-v2-r0c1.png', P+'char-coalthief-north4-v2-r1c0.png', P+'char-coalthief-north4-v2-r1c1.png'],
    subject: THIEF, sheet: sheet4, phases: phases4,
    facing: 'The reference shows him from directly behind, walking away from the viewer. Turn him a little to the right, a quarter turn, so that he walks toward the TOP-RIGHT CORNER of the picture: his back is still toward us and his face is NOT VISIBLE in any of the four drawings, but his boots and the brim of his hat now point up and to the right. The coal sack stays over his shoulder, trailing behind him on the LEFT side of the drawing.' },
  { id: 'thief-nw', family: 'coalthief', grid: '2x2', frames: 4, cell: 512, band: [246, 276], aim: 258, mode: 'halfway',
    refs: [P+'char-coalthief-north4-v2-r0c0.png', P+'char-coalthief-north4-v2-r1c0.png', P+'char-coalthief-sheet-walk4-a-r1c0.png', P+'char-coalthief-sheet-walk4-a-r1c2.png'],
    subject: THIEF, sheet: sheet4, phases: phases4,
    facing: 'The two references are the man seen from directly behind walking north away from the viewer and the man seen in left-facing profile walking west. Draw him exactly between them: walking NORTH-WEST, away from the viewer and toward the LEFT edge, his body turned 45 degrees so that his boots point to the upper left. His face is NOT visible, only the back and side of the hat brim and his shoulders. The coal sack trails behind him on the RIGHT side of the drawing.' },

  { id: 'school-e', family: 'schoolteacher', grid: '2x2', frames: 4, cell: 512, band: [301, 315], aim: 308,
    refs: [P+'char-schoolteacher-sheet-walk8-a-r2c0.png', P+'char-schoolteacher-sheet-walk8-a-r2c1.png', P+'char-schoolteacher-sheet-walk8-a-r2c2.png', P+'char-schoolteacher-sheet-walk8-a-r2c3.png'],
    subject: TEACHER, sheet: sheet4, phases: phases4,
    facing: 'In every cell she is seen in RIGHT-FACING SIDE PROFILE, walking east — her face, chest, knees and boot toes all point to the RIGHT edge of the cell, her back and the skirt hem trailing to the LEFT. This is the true opposite-side view of the reference (which faces left); it is NOT a mirrored copy — the satchel hangs on the hip nearest the viewer and trails slightly behind her.' },
];

export const SAME_ANGLE = 'The attached reference shows this same subject from ONE camera angle in four walk phases; copy its drawing, its costume and its technique exactly and change only what the heading above requires.';
export const HALFWAY = 'The attached reference sheet shows this same subject from the TWO camera angles either side of the one you must draw. Copy the costume, the palette and the drawing technique from the references — but NOT their camera angle: the new drawings are EXACTLY HALFWAY between the two reference angles, a true 45-degree three-quarter turn, the same 45 degrees in all four of them. Prove the turn in the drawing: the silhouette is visibly ASYMMETRIC about its vertical centre line, one side of the body is clearly nearer the camera and drawn larger than the other, and the near side overlaps the far side.';

export function buildPrompt(row) {
  const anchoring = row.mode === 'halfway' ? HALFWAY : SAME_ANGLE;
  return [row.sheet, RENDER, row.subject, row.facing, anchoring, row.phases, ANCHOR, SHEET_LAW].join(' ');
}
