import {chromium} from '@playwright/test';
import {writeFileSync,readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const arm=process.env.ARM??'after',raw='artifacts/sol/map-art-campaign-2/_raw/run-8/e10-archive-world-before';
const out='artifacts/sol/map-art-campaign-2/run-8/e10-archive-world',browser=await chromium.launch({channel:'chromium'}),rows=[];
try{for(const width of [1280,390]){const page=await browser.newPage({viewport:{width,height:width===390?844:800},isMobile:width===390,hasTouch:width===390}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});if(arm==='before'){
const config=JSON.parse(readFileSync(`${out}/capture-config.json`,'utf8'));
await page.route('**/src/world/Terrain3dClaimPilot.ts*',async route=>{const response=await route.fetch();let body=readFileSync(`${raw}/Terrain3dClaimPilot.js`,'utf8');const live=await response.text();const deps=new Map([...live.matchAll(/\/node_modules\/\.vite\/deps\/([^?"']+)\?v=[a-f0-9]+/g)].map(m=>[m[1],m[0]]));body=body.replace(/\/node_modules\/\.vite\/deps\/([^?"']+)\?v=[a-f0-9]+/g,(url,file)=>deps.get(file)??url);await route.fulfill({response,body})});
for(const asset of config.assets)await page.route(`**/${asset.name}*`,route=>new URL(route.request().url()).searchParams.has('import')?route.continue():route.fulfill({body:readFileSync(`${raw}/${asset.name}`),contentType:asset.type}));
for(const file of config.contracts)await page.route(`**/${file}*`,route=>{const contents=readFileSync(`${raw}/${file}`,'utf8'),isRaw=new URL(route.request().url()).searchParams.has('raw');return route.fulfill({body:isRaw?'export default '+JSON.stringify(contents):contents,contentType:isRaw?'application/javascript':'application/json'})});
}
await page.goto('http://127.0.0.1:5303/?debug&epoch=epoch-10-deepsky&contract=e10-archive-world&nowaves&nolevel&nopause&tier=full&seed=map-art-campaign-2');await page.waitForFunction(()=>document.querySelector('#game-canvas')?.dataset.terrain3dPilotLandmarkLoadState==='mounted');const begin=page.getByTestId('contract-briefing-dismiss');if(await begin.isVisible())await begin.click();await page.evaluate(()=>{window.__GR_TEST__.setManualSim(true);window.__GR_TEST__.advanceSim(Math.max(0,10-window.__THREE_GAME_DIAGNOSTICS__.timeAlive));window.__GR_TEST__.teleport(0,-63);window.__GR_GUI__?.hide()});await page.waitForTimeout(1200);await page.screenshot({path:`${out}/scenery-edge-${arm}-${width}.png`});const state=await page.evaluate(()=>({hero:window.__THREE_GAME_DIAGNOSTICS__.heroPos,dataset:{...document.querySelector('#game-canvas').dataset}}));assert.deepEqual(errors,[]);rows.push({width,state,errors,diagnostic:'Hero teleported to south edge (0,-63), ordinary camera and HUD; not an entry verdict.'});await page.close()}}finally{await browser.close()}writeFileSync(`${out}/scenery-edge-${arm}-proof.json`,JSON.stringify(rows,null,2)+'\n');
