// s1224 — ledger: the drain line, F-1224-3, F-1224-4, and the GZ-01 gazette item.
import fs from 'node:fs';

// ---- 1. BACKLOG: the drain line + the two new findings ---------------------
const P = 'tasks/BACKLOG.md';
const L = fs.readFileSync(P, 'utf8').split('\n');
const anchor = L.findIndex((l) => l.startsWith('- 🔬 **F-1224-1 (s1224)'));
if (anchor < 0) throw new Error('F-1224-1 anchor not found');

const shipped =
  '- ✅ **E2 RAIL-TOUGH-ONLY BIND SHIPPED `af232c57a0867aba6cc609e4dc75efef5f711cb8`** (s1224 drain, review `reviews/e2-rail-tough-only-bind.md`, leaf `e2-rail-tough-only-bind` → `merged`). **The eight-winds ladder lands its first E2 enemy, and it landed because a gate that was allowed to cancel the task said yes.** Scope 1 required proof that the sheet’s *repaired* front rows are a lawful mirror pair before any binding — a STOP there would have been a success, exactly as slice 3’s was. The runner measured it: **`0v1` wrench-excluded delta `-0.118521`** against F-1188-2’s **|0.095|** noise ceiling, with the already-settled **`2v3` pair reproduced as a positive control at `-0.127001`**, and **all nine declared shaft/jaw mask sizes mirror-dominant on both arms** (`-0.114271…-0.121988` and `-0.117634…-0.127001`). ➡️ **Bound `sw`/`se`/`nw`/`ne` on `char.e2.rail_tough.walk4` ONLY, and emptied that slot’s alias map** — `{ "se":"e","ne":"e","sw":"w","nw":"w" }` → `{}`. That is the trap that makes a correct edit do nothing: the alias pass runs **after** explicit directions and `SpriteAnimator.ts:843` exempts only `charHero`, so the aliases would have overwritten the new bind. The runner emptied the one slot rather than widening the `src/` guard — surgical and reversible, as the master demanded. **Steam Wrecker and Coal Thief are byte-untouched** (F-1193-3 still open, and binding either would ship the exact defect slice 3 stopped to prevent). ✓ **Gates RE-MEASURED on the merged tree, not copied from the runner:** tsc clean · build green (`✓ built in 1.61s`, asset diet `1099906/1500000`) · **node-guards 78/78** · `--list` **2468 tests in 345 files** (+2/+1 = the new spec × 2 projects) · own spec **2/2 both projects** · plain boot **zero console/page errors desktop AND 390 px**, asserted inside the new no-`?debug` spec · **zero `src/` bytes**. 🔢 **The guard count is the tell that re-measuring matters:** the runner read **76/76** against a **74** baseline — its own stale lane base — while main’s baseline had become **76** after s1222 added `bench-seeds.test.mjs`. The merged tree must read **78**, and does; both guards survived the one-file `package.json` 3-way graft. ⚠️ **The lane base `896a79c4` predates three merges, so `main..lane/m3` displays ~29,000 phantom deletions** (`bench-seeds.json`, `standings.ts`, two review files, the entire `logs/session-scratch/` tree). Classified against the **merge-base** instead: 29 lane-touched files, exactly **one** also moved by main.';

const f3 =
  '- 🔴 **F-1224-3 (s1224, non-blocking, RECORDED) — `e2e/wire-e2-enemy-walk4.spec.ts:15` IS A BASELINE RED ON MAIN IN BOTH PROJECTS AND IS IN NO TABLE ANYWHERE.** Surfaced by the rail-tough drain’s adjacent battery and then *attributed* rather than assumed: a control on **pre-merge main** (detached worktree at `b9918410`, served on scratch port **5236** because 5188 is shared with the live lane worktrees, and **validated over HTTP before use** — it serves the old contract with no `walkdiag4` cells) reproduced it **2/2**, matching the treatment’s **2/2**. **4/4 across two trees and two loads.** The spec’s E2 roster/motion half passes; the failure is its unrelated **E1** control timing out after five seconds on `char.bandit_base.loaded`. **Recorded as an APPENDED ADDENDUM to `logs/suite-red-inventory.md`, not as a table row** — those tables are generated by `scripts/suite-red-inventory.mjs` from a single whole-suite run and carry a reduction check that counts their own rows, so hand-inserting would falsify the artifact and its self-check together. **The cost of leaving it unrecorded is concrete: this drain spent a full control battery proving a red it did not cause, and the next E2-adjacent battery would have paid that same cost again.** Diagnosis of the E1 loader timeout is a separate slice.';

const f4 =
  '- 🔬 **F-1224-4 (s1224, non-blocking, PROCESS) — THE RUNNER’S ADJACENT-SUITE SELECTION MISSED THE SPEC NAMED FOR ITS OWN SUBJECT.** It ran `eight-winds-hero`, `lane-c-activations-assay-office` and `wire-e2-enemy-walk4` — but **not `e2e/e2-enemies.spec.ts`, whose own test title is *“wave pulses spawn **Rail Toughs**, Steam Wreckers, and Coal Thieves from E2 data”***. That spec carries **four** reds in both projects. Nothing shipped wrong — all four are pre-existing and already in the inventory at `:125` and `:317` — **but the battery was blind exactly where the slice was most likely to break something.** ➡️ **Corrective: derive adjacent-suite selection MECHANICALLY** — `grep -rl` the subject’s identifiers (`railtough`, `rail_tough`, `characters.v2`) across `e2e/` returns the eight specs this drain ran, and it costs one command. Choosing adjacent suites by hand is choosing them by memory, and memory is what the firewall lists exist to replace. 🔎 **A corroboration of F-1224-1 fell out of this:** the inventory keys those reds on their **assertion** lines (`:125`, `:317`) while playwright reports their **declaration** lines (`:113`, `:314`) — the same one-subject-two-coordinates split that let the `ap-standing-orders` label survive a sweep for three fires.';

L.splice(anchor, 0, shipped, f3, f4);
fs.writeFileSync(P, L.join('\n'));
console.log('BACKLOG: shipped line + F-1224-3 + F-1224-4 inserted at', anchor);

// ---- 2. GZ-01 gazette item (this merge IS player-visible) ------------------
const G = 'marketing/outbox/gazette-queue.md';
const item = `
## The Rail Tough Learns to Walk the Corners

Until now the rail gang's enforcer turned only four ways, and any diagonal approach was faked from a side view.
He walks the four corners properly now — southwest, southeast, northwest and northeast, each with its own set of frames drawn for that heading.
Two of his companions still wait their turn; the county does not put a man on the road until his footing is proven.
merge af232c57a0867aba6cc609e4dc75efef5f711cb8 · reviews/shots-e2-rail-tough-only-bind/desktop-chrome-rail-tough-4x.png
`;
fs.appendFileSync(G, item);
console.log('GZ-01: gazette item appended');
