import { readFileSync, writeFileSync } from 'node:fs';

const P = 'tasks/BACKLOG.md';
let t = readFileSync(P, 'utf8');
const before = t.length;

// ── 1. F-1508-2 main row → SHIPPED banner, original text preserved verbatim after it.
const oldHead = '🟡 **F-1508-2 (s1508 — `red-inventory-lookup.mjs` HAS TWO FALSE-VERDICT SURFACES, AND ONE OF THEM COST THIS FIRE ITS FIRST READING.** Non-blocking, fire-authorable.)';
const newHead = '✅ **F-1508-2 — SHIPPED s1513, merged `c7284596`** (gates: `tsc` rc=0 · `test:node-guards` **346 tests / 343 pass / 0 fail / 3 skipped**, the new arm `bare names are misuse and verdict dates track the compact snapshot` confirmed present in the raw output · `test:ledger-guards` **77/77** · no build/Playwright owed — the diff touches `scripts/` + `docs/` only, no `src/` run surface. **Both surfaces verified against a CONTROL arm rather than inherited:** on pre-merge main `node scripts/red-inventory-lookup.mjs 072-era-activation` → `NOT-IN-INVENTORY` rc=1; on the merged tree → `spec does not exist: …` **rc=2**. The date is derived, proven twice — `grep "2026-07-28"` on the script returns nothing, and the guard asserts a **`2031-12-25` fixture** date, so a hardcoded literal would red the battery. `--snapshot` resolves `eb3a8a012`, which I confirmed is the last main commit before `stats.startTime`. Review: `reviews/f1508-2-red-inventory-lookup-verdicts.md`.) **Originally filed as:** 🟡 **(s1508 — `red-inventory-lookup.mjs` HAS TWO FALSE-VERDICT SURFACES, AND ONE OF THEM COST THIS FIRE ITS FIRST READING.** Non-blocking, fire-authorable.)';
if (!t.includes(oldHead)) throw new Error('F-1508-2 head not found');
t = t.replace(oldHead, newHead);

// ── 2. dispatch row → drained.
const oldDisp = '📮 **F-1508-2 — MASTER AUTHORED + DISPATCHED s1511 → lane-b**';
const newDisp = '✅ **F-1508-2 — MASTER AUTHORED + DISPATCHED s1511 → lane-b, DRAINED s1513 (`c7284596`), leaf `merged`.**';
if (!t.includes(oldDisp)) throw new Error('F-1508-2 dispatch row not found');
t = t.replace(oldDisp, newDisp);

// ── 3. F-1510-3 — honest partial: the ARCHAEOLOGY is cured, the LITERAL gate is not.
const anchor = '**REC: write `HEAD` into the provenance block on the next regeneration of the inventory, and have `red-inventory-lookup` cite the denominator source. GATE: closes when the inventory names the commit it was taken at.**';
const replacement = anchor + ' 🟢 **PARTIALLY SATISFIED s1513 by f1508-2 (`c7284596`) — AND THE RESIDUE IS NAMED RATHER THAN WAVED THROUGH.** The master folded this row in as its scope 3 and described it as closing this finding; measured at the drain, it **cures the cost but does not meet the gate as written.** `node scripts/red-inventory-lookup.mjs --snapshot` now prints the run window and resolves the contemporaneous main commit mechanically (`SNAPSHOT main commit eb3a8a012…`, verified as the last commit before `stats.startTime`), so **the archaeology this row was filed about is gone** — no fire need timestamp-match by hand again. ⚠️ **But the gate sentence says *the inventory names the commit it was taken at*, and the inventory still does not** — the commit is DERIVED on demand from `stats.startTime`, not RECORDED in the provenance block. Those differ the moment the snapshot is regenerated by a process that rewrites `startTime`, or read by anything that is not this script. Half of the REC (the provenance-block write) is untouched. **This row therefore stays OPEN with its scope reduced to that one line, rather than being closed on a cure that satisfied its purpose but not its predicate** — counting a gate\'s conjuncts is exactly the failure class this ledger keeps re-learning. **GATE (unchanged, now cheap): closes when a regeneration of `logs/suite-red-inventory.md` writes `HEAD` into its provenance block.**';
if (!t.includes(anchor)) throw new Error('F-1510-3 anchor not found');
t = t.replace(anchor, replacement);

// ── 4. New row: F-1513-1.
const marker = '\n✅ **F-1507-2 — CLOSED s1510.';
const row = '\n🟢 **F-1513-1 (s1513 — A RUN REPORT TRANSCRIBED 3 SKIPPED TESTS AS PASSES.** Non-blocking, no corrective owed, recorded for the class.) The f1508-2 run report states `test:node-guards` gave *"346 tests / 346 pass / 0 fail / 0 cancelled / 0 skipped"*. Re-measured by me on the merged tree: **346 tests / 343 pass / 0 fail / 0 cancelled / 3 skipped**. ⓘ **The gate outcome is IDENTICAL either way** — `fail 0`, rc=0 — so this blocked nothing and the merge stands unaffected. It is recorded because in this factory *a skipped test is an invisible one*: `0 skipped` asserts full coverage, `3 skipped` says three arms never executed, and the difference is precisely what the vacuous-green findings ([F-1299-x], [F-1300-4]) are all about. The 3 skips look like a **standing property of the battery, not something this slice introduced** — `scripts/fire.md`\'s F-1460-1 note records the same shape at a smaller denominator (*"284 tests / 281 pass / 3 skipped"*). 💡 **REC: none beyond the obvious — paste tallies, never retype them.** No task owed. Related: [F-1508-2], [F-1300-4].\n';
if (!t.includes(marker)) throw new Error('F-1507-2 marker not found');
t = t.replace(marker, row + marker);

writeFileSync(P, t);
console.log('BACKLOG grew', t.length - before, 'chars; all 4 edits applied.');
