import {chromium,devices} from 'playwright';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const out=process.env.CLAW_OUT??'artifacts/boss-fidelity/e8-salvage-claw/production';await mkdir(out,{recursive:true});
const report={scope:'Actual production preview, public hooks, accelerated encounter; optimized response bytes checked against dist; persisted yard reload.',candidateOverride:process.env.CLAW_MODEL??null,triangleGuardOverride:process.env.CLAW_TRIANGLES??null,downloads:[],cases:[],errors:[]};
const browser=await chromium.launch({headless:true});
try{for(const tier of (process.env.CLAW_TIER?[process.env.CLAW_TIER]:['full','lite']))for(const device of ['desktop','mobile']){
 const page=await browser.newPage({...devices[device==='mobile'?'Pixel 5':'Desktop Chrome'],viewport:device==='mobile'?{width:390,height:844}:{width:1440,height:1000}});
 if(process.env.CLAW_TRIANGLES)await page.route(/\/src\/systems\/SalvageClawBossSystem\.ts(?:\?|$)/,async route=>{const response=await route.fetch(),body=(await response.text()).replace(/const MODEL_TRIANGLES = [\d_]+;/,`const MODEL_TRIANGLES = ${Number(process.env.CLAW_TRIANGLES)};`);await route.fulfill({response,body});});
 const downloads=[];page.on('response',r=>{const file=new URL(r.url()).pathname.split('/').at(-1);if(/^salvage-claw-detail-opus5-.*\.glb$/.test(file))downloads.push((async()=>{const bytes=await r.body(),built=await readFile('dist/assets/'+file),sha=b=>createHash('sha256').update(b).digest('hex');assert.equal(sha(bytes),sha(built));report.downloads.push({tier,device,url:r.url(),sha256:sha(bytes),bytes:bytes.length});})());});
 if(process.env.CLAW_MODEL){const body=await readFile(process.env.CLAW_MODEL),expected=createHash('sha256').update(body).digest('hex');await page.route('**/salvage-claw-detail-opus5.glb',route=>route.fulfill({body,contentType:'model/gltf-binary'}));page.on('response',r=>{if(new URL(r.url()).pathname.endsWith('/salvage-claw-detail-opus5.glb'))downloads.push((async()=>{const bytes=await r.body(),actual=createHash('sha256').update(bytes).digest('hex');assert.equal(actual,expected);report.downloads.push({tier,device,url:r.url(),sha256:actual,bytes:bytes.length});})());});}
 page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});
 await page.addInitScript(()=>{if(!sessionStorage.getItem('claw-production')){localStorage.clear();sessionStorage.setItem('claw-production','1');}});
 await page.goto(`http://127.0.0.1:5248/?debug&epoch=epoch-8-orbital&contract=e8-mare-claim&nowaves&nolevel&nopause&tier=${tier}&seed=claw-fidelity`);
 await page.waitForFunction(()=>window.__GR_TEST__&&window.__THREE_GAME_DIAGNOSTICS__?.contract.activeId==='e8-mare-claim');
 await page.evaluate(()=>document.querySelector('[data-testid=contract-briefing-dismiss]')?.click());
 await page.evaluate(()=>{const h=window.__GR_TEST__;h.setManualSim(true);h.setBalance('enemy.contactDamage',0);h.setBalance('sparkRig.range',0);h.setBalance('salvageClaw.arriveWave',4);h.setBalance('salvageClaw.dreadWaves',2);h.setBalance('salvageClaw.descentSeconds',.5);h.startWaveForTest(4);h.advanceSim(.1);});
 if(tier==='full')await page.waitForFunction(()=>document.querySelector('canvas').dataset.salvageClaw3dState==='ready');
 const center=await page.evaluate(()=>window.__GR_TEST__.enemyPositions().filter(e=>e.variantId==='salvage_claw').reduce((s,e,i,all)=>({x:s.x+e.x/all.length,z:s.z+e.z/all.length}),{x:0,z:0}));
 const shot=async state=>{await page.evaluate(({state,framed,center})=>{const h=window.__GR_TEST__,a=center;h.teleport(a.x,a.z+(framed?(state==='airborne'?-10:0):8));h.advanceSim(.05);},{state,framed:process.env.CLAW_FRAMED==='1',center});if(process.env.CLAW_FRAMED==='1'){await page.locator('canvas').dispatchEvent('wheel',{deltaY:2500,deltaMode:0,bubbles:true});await page.evaluate(()=>window.__GR_TEST__.advanceSim(.3));}await page.waitForFunction(()=>!Object.entries(document.querySelector('canvas').dataset).some(([k,v])=>['terrain3dPilotState','run3dPilotState'].includes(k)&&v==='loading'),{},{timeout:60000});await page.waitForTimeout(1500);await page.mouse.click(6,6);const data=await page.evaluate(()=>({boss:window.__THREE_GAME_DIAGNOSTICS__.salvageClawBoss,camera:window.__THREE_GAME_DIAGNOSTICS__.camera,canvas:{...document.querySelector('canvas').dataset}}));await page.screenshot({path:`${out}/${tier}-${device}-${state}.png`});report.cases.push({tier,device,state,...data});console.log(tier,device,state,data.boss.act);};
 await shot('airborne');
 for(const id of ['grapple_port','grapple_starboard','winch']){await page.evaluate(id=>{const h=window.__GR_TEST__,s=structuredClone(h.captureSuspend()),e=s.enemies.active.find(e=>e.variantId==='salvage_claw'&&e.bossComponentId===id);if(!e)throw Error('missing '+id);e.hp=.01;if(!h.restoreSuspend(s))throw Error('restore failed');const p=h.enemyPositions().find(e=>e.variantId==='salvage_claw'&&e.bossComponentId===id);h.setBalance('blast.damage',2);h.launchBlastAt(p.x,p.z,.05);h.advanceSim(.75);},id);if(id==='grapple_starboard')await shot('descending');}
 await shot('landed');assert.equal(report.cases.at(-1).boss.act,3);
 await page.evaluate(()=>{const h=window.__GR_TEST__,s=structuredClone(h.captureSuspend()),e=s.enemies.active.find(e=>e.variantId==='salvage_claw'&&e.bossComponentId==='anchor_feet');if(!e)throw Error('missing feet');e.hp=.01;if(!h.restoreSuspend(s))throw Error('restore failed');const p=h.enemyPositions().find(e=>e.variantId==='salvage_claw'&&e.bossComponentId==='anchor_feet');h.setBalance('salvageClaw.crewQuitSeconds',.5);h.launchBlastAt(p.x,p.z,.05);h.advanceSim(1);});
 await shot('yard');assert.equal(report.cases.at(-1).boss.carcassPresent,true);
 await page.reload();await page.waitForFunction(()=>window.__GR_TEST__&&window.__THREE_GAME_DIAGNOSTICS__?.salvageClawBoss?.persistentCarcass&&document.querySelector('canvas').dataset.salvageClaw3dState==='ready');await page.evaluate(()=>window.__GR_TEST__.setManualSim(true));await shot('fresh-yard');assert.equal(report.cases.at(-1).boss.persistentCarcass,true);
await Promise.all(downloads);if(tier==='full')assert(downloads.length>=2);await page.close();
}assert.deepEqual(report.errors,[]);report.completed=true;}catch(e){report.failure=e.stack;throw e;}finally{await writeFile(`${out}/report.json`,JSON.stringify(report,null,2));await browser.close();}
