import { readFileSync, writeFileSync } from 'fs';
const p = 'STATUS.md';
const lines = readFileSync(p, 'utf8').split('\n');
const old1 = lines[0]; // current ACTIVE s181 lock line
const stamp = '2026-07-08T00:25:00Z';
const h = `Last updated: ${stamp} s181 handoff, lock CLEARED — **DRAINED e3-power-graph-core** (lane/m3 \`bce5c63\` → merge \`d0f4204\`): dormant 471-line PowerGraph connected-component solver (\`?debug&power=dev\`), was ABSENT on main; base \`c15e250\` clean 3-way auto-merge, NO conflicts. GATE: tsc+build green; own spec **6/6** desk+mob (flag-off boot = zero graph work) + m1-01 4/4 + m2-01 6/6 + task-025 29/30. **The 1 red = F-181-1 (task-025:186 wet-powder), ATTRIBUTED TO CLEAN MAIN — NOT this merge:** the world-info-notes Prospector announcement \`"...follows and observes..."\` overwrites the transient \`ui.announcement\` field the test reads (string on \`f888a2e:src/game/Game.ts:3230\`; \`bce5c63\` touches ZERO announce code). It is now **DETERMINISTIC on desktop** (3/3 isolated), promoted from the ~⅔ flake fix-025 was authored against — world-info-notes (\`1612eab\`) made the Prospector note win the field. **fix-025 (queued main-slot) fully covers it** (rewrites :186 to poll the durable Wave-status DOM). Ledger+review committed \`bccfba2\` (\`reviews/e3-power-graph.md\`). Backup pushed origin (→bccfba2). Deploy: permission-blocked headless + merge is dormant (no player-facing change) → no-op. **BOARD:** lanes b/c/d LIVE (b=054-baron-epic pid39243, c=contract-briefings pid7158, d=gt-05-water-depth pid7168) — each has a queued follow-up (\`town-t4\`/\`world-info-notes\`/\`stamp-site-read\`) that runs on codex exit; DON'T touch them. lane-a IDLE + DRAINED (lane/m3 0-ahead). Assayer pending EMPTY. **NEXT FIRE:** A. **Drain lanes b/c/d AS each done-moves AND its codex EXITS** (gate-contamination — never gate a live pid); serial, oldest-first, full battery each. B. **Drain fix-025 main-slot output** once it runs (test-only, task-025:186 → durable DOM, \`--repeat-each\` proof — note it now flips a HARD desktop red, not just a flake). C. **PIPELINE-DRY: lane-a** — its next work (E2 ③ science-tree) is architecturally BLOCKED pending attended's \`e2-science-socket\` ENGINE slice (s178: EpochBundle has no research-node channel); E3-ahead engine work violates Template Law (E3 = two epochs past shipped E1). Refill lane-a ONLY after attended authors the socket. D. Robin owes (nag, don't block): **e2-science-socket design fork** (node typing on EpochManifest/Bundle + ResearchChart static-⊎-epoch merge) = the lane-a unblocker; turret-feel + water-feel playtest verdicts; Mac full-regression evidence; favicon 16px. NOTE: dozens of tracked \`artifacts/*.png\` + \`logs/dashboard.html\` still uncommitted from attended — harmless, whitelisted by fix-025; attended to commit-or-discard.`;
const archive = `- **s181 lock (line-1 archive):** ${old1.replace(/^Last updated: /, '')}`;
const out = [h, archive, ...lines.slice(1)].join('\n');
writeFileSync(p, out);
console.log('handoff written; s181 lock archived');
