#!/usr/bin/env bash
# Gold Rush factory watchdog — deterministic, no AI, watches the watchers.
# Modes: (no arg) = one health pass (launchd runs this every 10 min)
#        status   = print a human dashboard and exit (safe anytime)
# Auto-remediation is limited to ONE safe action: restarting a dead runner
# (single-instance lock in lane-runner-v3.sh makes this race-free).
# Everything else = observe + notify (macOS notification + logs/health.log).
# OpenClaw or any other notifier may READ logs/health.log; nothing but this
# script writes it, and this script never writes the repo ledger (STATUS.md).
set -u
ROOT="/Users/robin/Claude/Projects/Gold Rush"
LOG="$ROOT/logs/health.log"
STATE="$ROOT/logs/.health-state"
mkdir -p "$ROOT/logs"
cd "$ROOT" || exit 1
. "$ROOT/scripts/runner-processes.sh"

ts() { date +%H:%M:%S; }
note() { echo "[health] $(date +%F) $(ts) $*" >> "$LOG"; }
alert() {
  note "ALERT: $*"
  osascript -e "display notification \"$*\" with title \"Gold Rush factory\"" >/dev/null 2>&1 || true
}

runner_alive() { [ -n "$(runner_pids)" ]; }

# F-2137-1: annotate the runner line when the live process predates the runner script's
# newest commit. Silent when current, so a healthy board reads exactly as it always has.
runner_staleness_note() {
  local pid n
  pid=$(runner_pids | head -1)
  [ -n "$pid" ] || return 0
  n=$(runner_inert_commits "$pid" "$ROOT" "$ROOT/scripts/lane-runner-v3.sh")
  [ "${n:-0}" -gt 0 ] || return 0
  printf ' ⚠️  STALE — pid %s predates %s commit(s) to lane-runner-v3.sh; they are INERT until restart (scripts/start-lane-runner.sh)' \
    "$pid" "$n"
}
fire_proc()    { pgrep -f "claude -p # Gold Rush FIRE" >/dev/null 2>&1; }

queued_count()  { ls tasks/queue/main tasks/queue/lane-* tasks/queue/art 2>/dev/null | grep -c '\.md$'; }
running_count() { ls tasks/running/ 2>/dev/null | grep -c -- '--'; }
pending_count() { ls assets/crafting-queue/pending/ 2>/dev/null | grep -c '\.json$'; }
failed_sig()    { ls tasks/failed/ 2>/dev/null | tail -5 | shasum | cut -c1-12; }
# Art-slot retention exposure (F-1045-1, s1045). worktrees/art/ is a PLAIN
# DIRECTORY, not a git worktree — so no `git status` anywhere in this repo can
# ever mention what is staged there. Files staged and never drained exist in no
# object database at all, on one disk. The s1045 sweep found 10, oldest 14 days.
# Counts bytes that are in NO object database — NOT "absent from main". Art
# parked on a save/* branch pending an owner verdict is preserved, and must not
# keep ringing: this condition persists until a human acts, so a false positive
# here trains everyone to ignore the one alarm that means permanent loss.
# Cheap by construction: the name set-diff vs main is one git call, and only
# that handful gets hashed (not all ~190 staged files, ~600 MB, every 10 min).
# F-1658-2 (s1658): THIS FUNCTION IS WHY THE RETENTION LAW'S LARGEST HOLE SAT
# UNSEEN FOR ~106 FIRES. It fed both the dashboard line and the edge-triggered
# alert below, and it reported `0` while 583 files / 527.89 MB died with this
# disk — measured live at s1658 against `art-staging-audit.mjs`, which said 582
# at the same instant (the audit had its own blind spot, F-1658-3).
#
# It carried BOTH defects the audit had already been fixed for:
#   - it read only `worktrees/art/assets/raw`, NON-recursively, while the ART
#     slot writes to four sibling dirs and 100% of the live exposure is nested
#     under `motion-pilot/` (F-1120-2);
#   - it pre-filtered by NAME via `comm` against `ls-tree main -- assets/raw/`,
#     so regenerated bytes under a tracked name were dropped before the blob
#     check could ever see them (F-1054-1).
# F-1640-1 calls the silence a mystery and notes no rule obliged anyone to run
# the audit. This is the mechanical answer: the board itself printed zero, and
# an alert edge-triggered on a count that never leaves 0 can never fire.
#
# Enumerated + recursive + classified by BLOB, batched through two git plumbing
# processes rather than one per file (~10s over 983 files, fine for a 10-min loop).
# (983 was the count BEFORE F-2175-1 widened the walk below; it is 1019 now. The
# old figure is restated rather than replaced — the drift is the provenance.)
# F-2175-1 (s2175): the THIRD site of F-2174-1's class, and the worst of the three.
# This function used `-not -path '*/.*'`, which excludes every path with a
# dot-prefixed segment — so all 36 `.hero-*-take[123].png` files (12.43 MB, every
# one in NO object database) were dropped BEFORE the blob check, and this alarm
# reported 0. s2174 cured the blanket dot-skip in `art-staging-audit.mjs` and
# `salvage-art-staging.mjs` and guarded THOSE TWO against drift; a third
# implementation of the same question, in another language, sat outside that
# guard's denominator. Measured s2175: scanned 983 with the exclusion vs 1019
# without; reported 0 vs a true 36.
#
# The irony is load-bearing and is why this is cured rather than noted: the
# comment directly above already states the principle — an edge-triggered alert
# on a count that never leaves 0 can never fire — while the code below it
# guaranteed exactly that for dot-prefixed art. Skip VCS/OS noise BY NAME, which
# is the same rule its two sibling scripts now carry (SKIP_NAMES).
art_untracked() {
  # F-2195-1 (s2195): scan `worktrees/art`, NOT `worktrees/art/assets`. A file at
  # the worktree root — one level above the staging tree — was never scanned by
  # any of the three implementations of this question, and the live casualty was
  # the ART slot's own README.md, 120 bytes in no object database for 48 days.
  # This is the ALARM, so its blindness is the worst of the three: it
  # edge-triggers on the count and a count that never leaves 0 can never fire.
  [ -d worktrees/art ] || { echo 0; return; }
  find worktrees/art -type f \
    -not -path '*/.git/*' -not -name '.git' \
    -not -name '.DS_Store' -not -name '.localized' -not -name 'Thumbs.db' 2>/dev/null \
    | git hash-object --stdin-paths 2>/dev/null \
    | git cat-file --batch-check 2>/dev/null \
    | grep -c 'missing' || true
}

# F-OUT-0829: agenttown.app answered Cloudflare 521 for ~2d18h (nginx died at an
# unattended-upgrade restart, 2026-08-26 06:09 UTC) and NOTHING in this factory
# noticed — every check above watches the Mac, none watched the public door. The
# three probes cover the three failure domains: landing (droplet nginx static),
# game (Cloudflare edge worker -> pages.dev), api (droplet nginx -> ledger/forward).
# F-2355-1: `curl -w '%{http_code}' ... || echo 000` CONCATENATES, it does not
# substitute. -w has already written the code to stdout by the time curl's exit
# status is known, so a request that receives a status and THEN fails mid-transfer
# captures both and yields an undocumented composite. Measured s2355 against the
# live door: a 200 that misses the -m budget prints exactly `200000`, and a request
# that never answers prints `000000`. Neither consumer could decode that — both
# read "not 200" and cried DARK for a door that had answered. The `|| echo 000`
# arm can never REPLACE the output, only corrupt it; capture the code and the
# transfer outcome SEPARATELY instead, and give the third state its own name.
edge_one() {  # -> 200 | 2xx-slow (answered, transfer missed the budget) | <code> | 000
  local c rc
  c=$(curl -so /dev/null -m 10 -w '%{http_code}' "$1" 2>/dev/null); rc=$?
  [ -n "$c" ] || c=000
  if [ "$rc" -eq 0 ]; then echo "$c"; return; fi
  case "$c" in
    2??) echo "$c-slow" ;;   # the door answered; the body did not finish in time
    *)   echo "$c" ;;        # 000 = nothing came back; anything else is its own bad code
  esac
}

edge_probe() {
  local l g a
  l=$(edge_one https://agenttown.app/)
  g=$(edge_one https://agenttown.app/goldrush/)
  a=$(edge_one https://agenttown.app/api/stats)
  echo "landing=$l game=$g api=$a"
}

dashboard() {
  echo "=== Gold Rush factory — $(date '+%F %H:%M:%S') ==="
  echo "edge   : $(edge_probe)   (200 = up; 2xx-slow = answered but missed the budget; anything else is dark — F-OUT-0829)"
  # F-2137-1: ALIVE is not the same as CURRENT. A runner executes the parse it loaded at exec
  # time, so commits to lane-runner-v3.sh since are INERT — the state in which the factory
  # refused a correct master 64 times in 12 min while three fires read the cure in the file
  # and believed it live. Reported HERE because this is the one command every session runs
  # at start (CLAUDE.md §1.4); a verdict only helps the reader who was going to look anyway.
  echo "runner : $(runner_alive && echo ALIVE || echo DEAD)$(runner_staleness_note)"
  echo "fire   : $(fire_proc && echo RUNNING || echo between-fires)"
  echo "lock   : $(head -c 120 STATUS.md)"
  echo "queued : $(queued_count) task(s)   in-flight: $(running_count)   pending-orders: $(pending_count)"
  # "ahead" counts COMMITS, which is not the same as undrained WORK: a
  # path-scoped squash merge lands the content on main and leaves the lane
  # commit behind forever, so a merged lane reads as "ahead" for good.
  # Verify by content before believing this line (Mistake #16):
  #   git show --stat <sha>   then   git diff --stat <branch> main -- <its files>
  # Empty diff on the touched files = SAFE DUPE, not a drain.
  echo "lanes ahead of main (commit count — may be squash-merged dupes, verify by content):"
  # F-1536-1 (s1536): the lanes are resolved from git, never hardcoded — the old list
  # named lane/m3..lane/m6-r3a-apply and reported two phantom lanes ahead while saying
  # NOTHING about lane/a..lane/d, which is where the lanes actually live.
  . "$ROOT/scripts/lane-branches.sh"
  LANE_BRANCHES="$(lane_branches)"
  [ -z "$LANE_BRANCHES" ] && echo "  (no lane worktree resolved — check 'git worktree list')"
  for b in $LANE_BRANCHES; do
    n=$(git log --oneline "main..$b" 2>/dev/null | wc -l | tr -d ' ')
    [ "${n:-0}" != "0" ] && echo "  $b: $n commit(s) ahead"
  done
  echo "art staged, in NO commit: $(art_untracked) file(s)  (detail: node scripts/art-staging-audit.mjs)"
  echo "failed tail: $(ls tasks/failed/ 2>/dev/null | tail -1)"
  echo "last fire log line: $(tail -1 "logs/fire-$(date +%Y%m%d).log" 2>/dev/null | head -c 120)"
}

if [ "${1:-}" = "status" ]; then dashboard; exit 0; fi

# ---- health pass ----
# 1. Runner dead -> restart headless (the one auto-remediation).
if ! runner_alive; then
  alert "Runner was DEAD — restarting it headless"
  # s1653 (F-1653-1): route through start-lane-runner.sh, which resolves a floor-meeting codex,
  # prepends its bin dir to PATH (so the lane's node/npm/npx match the gate baseline) and scrubs
  # CLAUDE_CONFIG_DIR/CLAUDECODE. The bare `nohup bash scripts/lane-runner-v3.sh` that stood here
  # inherited this job's PATH — launchd's, with no nvm — i.e. the exact under-floor restart that
  # cost the factory ~5h03m on 2026-08-11 (F-1652-1), performed automatically and unattended.
  # The helper detaches and verifies on its own, so it is NOT backgrounded here.
  bash scripts/start-lane-runner.sh >> logs/runner-headless.log 2>&1
  sleep 2
  runner_alive && note "runner restarted ok (headless, log: logs/runner-headless.log)" \
               || alert "runner restart FAILED — needs a human"
fi

# 2. Starvation: work queued, nothing running, runner alive (two passes in a row).
QC=$(queued_count); RC=$(running_count)
STARVED_BEFORE=$(grep -c '^starved' "$STATE" 2>/dev/null || echo 0)
if [ "$QC" -gt 0 ] && [ "$RC" -eq 0 ] && runner_alive; then
  if [ "$STARVED_BEFORE" -gt 0 ]; then
    alert "Starvation: $QC task(s) queued, runner alive but idle for 2+ checks"
  fi
  echo "starved" >> "$STATE"
else
  grep -v '^starved' "$STATE" > "$STATE.tmp" 2>/dev/null; mv "$STATE.tmp" "$STATE" 2>/dev/null || : > "$STATE"
fi

# 3. Stale fire lock: STATUS line-1 ACTIVE + no fire process + file untouched >50 min.
# F-1659-2 (s1659): this asks the SAME question as the runner's main-slot lock gate
# (lane-runner-v3.sh:213) and used to ask it with its own anchored-prefix regex,
# '^Last updated.*ACTIVE\|^ACTIVE'. F-1402-1 cured the runner's copy and nobody brought
# this one along — the sibling-script class. Measured against all of STATUS.md's archives:
#   old predicate: 134/1432 handoff archives FALSE-POSITIVE (a cleared lock read as live),
#                  and — the serious half — 11/324 real ACTIVE lock lines MISSED, because
#                  the anchors cannot see 's908 fire, lock ACTIVE' or a doubled stamp.
#                  Over the last 100 fires alone: 15 false positives in 98 handoffs.
#   this one:      0 missed locks (324/324), 0 false positives over the last 100 fires.
# A missed lock is a SAFETY failure: check 3 is the only thing that reports a dead lock,
# and §1.1 tells the next fire to exit silently while one stands. Keep this predicate
# byte-identical in shape to the runner's; scripts/main-lock-gate-guard.test.sh evaluates
# BOTH by extraction against one shared fixture set, so they cannot drift apart again.
l1="$(head -1 STATUS.md)"
if [[ "$l1" == *ACTIVE* && "$l1" != *"lock CLEARED"* ]] && ! fire_proc; then
  if [ -n "$(find STATUS.md -mmin +50 2>/dev/null)" ]; then
    alert "Fire lock looks DEAD (ACTIVE >50min, no fire process) — next fire should reclaim; watch it"
  fi
fi

# 4. Runaway pending orders.
PC=$(pending_count)
[ "$PC" -gt 5 ] && alert "Crafting pending/ has $PC orders — runaway-generator class"

# 5. New failures since last pass.
SIG=$(failed_sig)
OLDSIG=$(grep '^failedsig=' "$STATE" 2>/dev/null | tail -1 | cut -d= -f2)
if [ -n "${OLDSIG:-}" ] && [ "$SIG" != "$OLDSIG" ]; then
  alert "New entries in tasks/failed/ — check $(ls tasks/failed/ | tail -1)"
fi
grep -v '^failedsig=' "$STATE" > "$STATE.tmp" 2>/dev/null; mv "$STATE.tmp" "$STATE" 2>/dev/null || : > "$STATE"
echo "failedsig=$SIG" >> "$STATE"

# 6b. Art-slot retention exposure (F-1045-1). Edge-triggered on the COUNT, not
# level-triggered: the condition persists until a human/fire salvages, and an
# alert every 10 min would train everyone to ignore it.
AU=$(art_untracked)
OLDAU=$(grep '^artuntracked=' "$STATE" 2>/dev/null | tail -1 | cut -d= -f2)
if [ "${AU:-0}" -gt 0 ] && [ "${AU:-0}" != "${OLDAU:-}" ]; then
  alert "ART slot: $AU staged file(s) in NO commit (was ${OLDAU:-unrecorded}) — preserve with: node scripts/salvage-art-staging.mjs save/<name>"
fi
grep -v '^artuntracked=' "$STATE" > "$STATE.tmp" 2>/dev/null; mv "$STATE.tmp" "$STATE" 2>/dev/null || : > "$STATE"
echo "artuntracked=$AU" >> "$STATE"

# 6. Codex auth wall showing in recent fire log.
if tail -40 "logs/fire-$(date +%Y%m%d).log" 2>/dev/null | grep -q '401 Unauthorized'; then
  alert "Codex 401 in recent fire log — account/login needs attention (codex login)"
fi

# 7. Public edge dark (F-OUT-0829). Alert on the DOWN edge, nag hourly while it
# stays down (a dark public door is the one condition worth re-ringing), and note
# recovery once. A 521 here previously ran ~2d18h with zero alarms.
EDGE="$(edge_probe)"
# F-2355-1: DARK and SLOW are different conditions and must not share one alarm.
# A door that answers 200 and then misses the transfer budget is DEGRADED, not
# down — and paging for it every time it happens is exactly how an alarm gets
# excused into uselessness (F-1460-1), which this factory cannot afford on the
# only watch it has over the public door. So: dark pages at once, as it always
# has; slow pages only once it has PERSISTED across 3 passes, which still catches
# a door that has genuinely stalled (headers sent, body never finishing).
EDGE_DARK="$(echo "$EDGE" | tr ' ' '\n' | grep -v -e '=200$' -e '\-slow$' | tr '\n' ' ')"
EDGE_SLOW="$(echo "$EDGE" | tr ' ' '\n' | grep -e '-slow$' | tr '\n' ' ')"
# F-2356-1: DARK and SLOW need SEPARATE CLOCKS, not one shared counter. The
# F-2355-1 cure gave them separate branches and separate mails but left them
# incrementing ONE `edgebad` tally, then chose the branch AFTERWARDS — so a dark
# door inherited however many passes the SLOW condition had already banked, and
# `[ EDGEN -eq 1 ]` could not fire. The comment three lines up promises "dark
# pages at once, as it always has"; measured s2356 by manufacturing the sequence,
# that promise held only from a cold state. Two slow passes then dark = 30 min of
# silence here, and 45 min on the droplet's 5-min timer (up to 50 after one slow
# pass). The shared counter predates F-2355-1 — what that cure changed is that
# the early passes are now DELIBERATELY silent, so the sequence load -> slow ->
# down, which is the ordinary way a box fails, now pages NOTHING at all until the
# modulo comes round. A per-condition clock makes each transition start at 1.
OLDDARKN=$(grep '^edgedark=' "$STATE" 2>/dev/null | tail -1 | cut -d= -f2)
OLDSLOWN=$(grep '^edgeslow=' "$STATE" 2>/dev/null | tail -1 | cut -d= -f2)
DARKN=0
SLOWN=0
if [ -n "$EDGE_DARK" ]; then
  DARKN=$(( ${OLDDARKN:-0} + 1 ))
  if [ "$DARKN" -eq 1 ] || [ $(( DARKN % 6 )) -eq 0 ]; then
    alert "PUBLIC EDGE DARK: $EDGE — runbook F-OUT-0829: ssh root@<droplet> 'systemctl status nginx goldrush-ledger'"
  fi
elif [ -n "$EDGE_SLOW" ]; then
  SLOWN=$(( ${OLDSLOWN:-0} + 1 ))
  if [ "$SLOWN" -eq 3 ] || [ $(( SLOWN % 12 )) -eq 0 ]; then
    alert "PUBLIC EDGE SLOW x$SLOWN passes: $EDGE — answered, transfer missed the budget. Not dark; check droplet load before the F-OUT-0829 runbook."
  fi
else
  # Announce recovery only for an episode that actually PAGED. Dark pages on its
  # first pass, slow on its third, so those two tests are exact — and without
  # them a one-pass slow blip that deliberately said nothing still mails an
  # all-clear for an alarm the owner never received.
  if [ "${OLDDARKN:-0}" -gt 0 ] || [ "${OLDSLOWN:-0}" -ge 3 ]; then
    alert "Public edge recovered: $EDGE"
  fi
fi
# `edgebad` is the retired F-2355-1 key: strip it too, so a state file written by
# the previous revision cannot leave a stale tally behind the new counters.
grep -v -e '^edgebad=' -e '^edgedark=' -e '^edgeslow=' "$STATE" > "$STATE.tmp" 2>/dev/null; mv "$STATE.tmp" "$STATE" 2>/dev/null || : > "$STATE"
echo "edgedark=$DARKN" >> "$STATE"
echo "edgeslow=$SLOWN" >> "$STATE"

note "ok runner=$(runner_alive && echo 1 || echo 0) queued=$QC inflight=$RC pending=$PC edge=$EDGE"
