import fs from 'node:fs';
const p = '/Users/robin/Claude/Projects/Gold Rush/tasks/BACKLOG.md';
const lines = fs.readFileSync(p, 'utf8').split('\n');
const i = lines.findIndex((l) => l.startsWith('- 🟡 **F-1476-1 (s1476, drain of'));
if (i < 0) { console.error('anchor row not found'); process.exit(2); }
if (lines.some((l) => l.includes('F-1477-1 (s1477'))) { console.log('already filed'); process.exit(0); }

const row = '- 🟡 **F-1477-1 (s1477, measured while curing F-1476-1) — THE RENDERER-COUNT JSONs ARE ONLY 2 OF THE 12 TRACKED FILES THESE SPECS DIRTY. THE OTHER 10 ARE SCREENSHOTS, AND **0 OF 10 ARE BYTE-IDENTICAL ACROSS TWO CONSECUTIVE RUNS** — SO CLOSING F-1476-1 WILL NOT END THE CHURN IT CITES AS ITS MOTIVATION.** F-1476-1 justifies itself by the F-1407-1 artifact-churn class: *"any lane or fire running this spec is left with 12 dirty tracked files, which can trip a pre-flight\'s clean-vs-main test."* ✓ **The 12 is confirmed** (measured s1477 in a detached worktree after running both specs at `--workers=1`: 12 modified tracked files). ⚠️ **But the composition was never broken down, and it decides whether the cure works.** For the crawler+railcar pair the 12 are **10 PNGs + 2 JSONs**. `artifacts/s1477-noise/png-churn.mjs` ran both specs twice back-to-back on an unchanged tree and SHA-compared every screenshot: **0/10 identical** — all ten changed, every file, every run (e.g. `desktop-chrome-intact.png` `0891ce693800` → `33d733fdc690`). ➡️ **THEREFORE THE F-1476-1 CURE, WHICH IS CORRECTLY SCOPED TO THE JSONs, FIXES 2/12 AND A PRE-FLIGHT WILL STILL TRIP ON THE REMAINING 10.** This is the guard-denominator-narrower-than-the-cure shape: the finding\'s stated motivation is wider than the subject its gate names, so satisfying the gate honestly can still leave the motivating problem in place — and a reader who sees F-1476-1 go ✅ would reasonably conclude the churn is gone. 🧭 **The two halves genuinely want DIFFERENT cures, which is why they are two findings and not one task.** The JSON half is curable by recording what is reproducible (exact deltas + measured tolerance bands — F-1476-1, queued s1477), because the numbers carry real signal. Screenshots are **irreducibly non-deterministic** at byte level, so the honest options for the PNG half are: stop tracking them and retain them as untracked evidence under the RETENTION LAW\'s mirroring rule; or keep them tracked and stop treating a dirty `artifacts/**` as a pre-flight failure; or compare them perceptually rather than by byte. **All three are policy choices with a cost, so this is a RULING, not a mechanical fix.** **GATE: closes when a ruling picks one of the three for tracked screenshot evidence AND the pre-flight clean-vs-main test is reconciled with it.** ⓘ Scope note, stated so nobody over-reads this: measured for `wire-crawler-3d` + `wire-railcar-3d`, `desktop-chrome`, this machine. Other specs that write screenshots are **unmeasured** and are likely the same class.';

lines.splice(i, 0, row, '');
fs.writeFileSync(p, lines.join('\n'));
console.log('filed F-1477-1 above F-1476-1 at line ' + (i + 1));
