import fs from 'node:fs';
const p = '/Users/robin/Claude/Projects/Gold Rush/tasks/BACKLOG.md';
const lines = fs.readFileSync(p, 'utf8').split('\n');
const i = lines.findIndex((l) => l.startsWith('- 🟡 **F-1476-1 (s1476, drain of'));
if (i < 0) { console.error('F-1476-1 row not found'); process.exit(2); }
if (lines[i].includes('MEASURED s1477')) { console.log('already updated'); process.exit(0); }

lines[i] += ' 📐 **MEASURED s1477 — THE DENOISED STATISTIC THE GATE ASKED FOR NOW EXISTS, AND IT CORRECTS THIS ROW ON ONE POINT OF RECORD.** `artifacts/s1477-noise/REPORT.md` (`1b64d48b1`): **crawler n=12, railcar n=10, one commit `2822069b5`, instrument pinned, `--workers=1`, same shell** — subject fixed, so any spread IS the band. **(1)** Most metrics are already byte-stable: **18 of 20** (crawler), **10 of 18** (railcar). **(2)** `geometries`/`textures` jitter is **COMMON-MODE — every phase-to-phase delta is EXACT** (all 6 railcar phase pairs, single value across all 10 runs: `geometries` 8, 5, 5, −3, −3, 0). The absolutes move; the differences do not, which is why the railcar spec’s live `geometries - baseline.geometries < 8` assertion is sound and has never flaked. **(3)** `calls`/`triangles` jitter **independently per phase**, with a `+1 call ⟺ +2 triangles` signature in **every** sample of **both** specs — the fingerprint of a single 2-triangle quad present or absent in the sampled frame, i.e. a sampling race rather than a rendering change. ⚠️ **THE CORRECTION: this row recorded `geometries 80→81` as "stable across both runs… unattributed and NOT bisectable". At n=12 `coldBaseline.geometries` is HARD-STABLE at 81 (12/12), so it was never the noisy component — it is a reproducible property of the commit and IS attributable.** ⚠️ **AND THE TRAP THE MEASUREMENT EXPOSED: a metric cannot be classified by its NAME.** The same `geometries` is hard-stable in the crawler’s `coldBaseline` and noisy in **four** railcar phases — noise is a property of the **(spec, phase, metric) triple, measured**, so any global whitelist is wrong on this evidence. ✓ **VERIFIED s1477 and load-bearing for the choice of cure: NOTHING READS THESE FILES** — `git grep renderer-count` over all tracked files returns the two specs that WRITE them and otherwise only prose (reviews, BACKLOG, STATUS, masters). No consumer, no guard, no assertion against the committed JSON. ➡️ **CURE QUEUED s1477 as gate disjunct (a), not (b): `tasks/lane-f1476-1-renderer-count-tolerance.md` → lane-a**, goal leaf `f1476-1-renderer-count-tolerance`. **(a) beats (b) because the deltas are exact and carry the regression signal, so "stop writing them" would discard real evidence to fix churn** — the task records exact values + exact deltas, bands with provenance for the jittery triples, and makes an out-of-band value FAIL loudly, converting a write-only churn source into an actual guard. **`mobile-chrome` remains UNSAMPLED — the master orders the runner to measure it (n≥8) rather than copy the desktop bands.** The closing prohibition below still stands and is restated in the master: do NOT refresh the old-format baselines as a drive-by.';

fs.writeFileSync(p, lines.join('\n'));
console.log('updated F-1476-1 row at line ' + (i + 1));
