import fs from 'node:fs';

const line1 =
  'Last updated: 2026-08-10T08:35Z s1620 handoff, lock CLEARED — ' +
  '🎯 **THREE DRAINS, THE FULL BUDGET, AND THE BOARD WENT FROM THREE UNDRAINED OUTPUTS TO ZERO.** ' +
  '`beb926087` f1619-1 (advance-stream cache reuse, lane-c) · `48f217502` minds-and-rigs (lane-b, **attended-authored**, player-visible) · `79782c6b4` f1619-2 (asset-diet town-budget A/B, lane-a). ' +
  'All three gated on the MERGED tree in a detached worktree (§3.0b), `--workers=1`, each merged-and-committed as ONE act per F-1589-5 — no merge was ever left staged on main. ' +
  '📋 **BOARD ON ARRIVAL (08:00):** lock CLEARED (s1619, owning commit `29ae20022` — judged by the COMMIT per §1.1, never by stamp text) · all six queues EMPTY · **two undrained done-moves waiting** (f1619-1, minds-and-rigs) and lane-a still BUSY on f1619-2, which finished mid-fire and became drain 3 · no `tasks/CODEX-WALL` · assayer `pending/` **0** · ART untouched, no staging audit owed. ' +

  '⭐ **[F-1620-2] THE HEADLINE, AND IT IS A NARROWING RATHER THAN A DISCOVERY — F-1616-3 IS ANSWERED ONLY HALF-WAY, AND THE PROBE COULD NOT HAVE DONE BETTER.** ' +
  'f1619-1 asked whether the advance stream re-downloads assets because `page.route` bypasses the cache, or as a real property of play. ✓ **NOT an interception artifact**: with zero interception it reproduces identically across **four independent runs** (runner ×2 projects, drain ×2 projects) — `menu 0 · town 10 · contract1 7 · town-return 10 · contract2 2` DOUBLE-DOWNLOAD, **CACHE-HIT 0 everywhere**. ' +
  '⚠️ **BUT `CACHE-HIT = 0` — the most persuasive number in the table — IS FORCED BY THE HARNESS AND IS NOT EVIDENCE ABOUT THE PREFETCH AT ALL.** ✓ **VERIFIED at the drain by probing the server directly rather than by reading the runner report:** `playwright.config.ts:69` runs `npm run dev`, and that Vite server answers a GLB `cache-control: no-cache` with a weak ETag, conditional replay → **`304`**. Under `no-cache` the browser MUST revalidate, so a true cache hit is **impossible by construction**. The zero was decided by the server before the prefetch was ever consulted. ' +
  '➡️ **So the defensible verdict is "NOT AN INTERCEPTION ARTIFACT", not "real property of play"; production headers (Cloudflare Pages, `immutable`) are UNMEASURED.** 💡 *An A/B that eliminates the suspect you thought of still inherits every suspect you did not — and the confound lived in the HARNESS, where neither the subject nor the instrument could show it.* ⓘ **The runner reached this limit unprompted and said so; the drain verified it rather than inheriting it.** ' +

  '🔧 **[F-1620-1] AND THE HEADLINE COUNT IS 18, NOT 29 — DO NOT PIN A REGRESSION ON 29.** ✓ VERIFIED by reading the code: `classify()` captures `response.status` at `:68` and **never reads it**, so 304 revalidations (~127 bytes, body served from cache) score as DOUBLE-DOWNLOAD. Splitting by transfer size: desktop **11 revalidation-sized + 18 genuine full re-transfers (~46.0 MB)**; mobile **15 + 14 (~42.3 MB)**. The defect is still large and real — a five-door walk re-transfers ~46 MB it had already fetched — but the label was wrong, not the measurement, and the artifact carries the raw bytes to recompute. ' +

  '⚠️ **[F-1620-7] THE SECOND-BIGGEST FINDING CAME OUT OF THE SMALLEST SLICE: THE 25 MB TOWN BUDGET IS GUARDED BY TWO INSTRUMENTS 9.5 MB APART.** `e2e/asset-diet.spec.ts` asserts `townResponseBytes < 25_000_000` **twice** — the pre-existing throttled-cues test at `:103` reports mobile **12,932,580** (12 MB headroom) while f1619-2\'s new normal arm at `:225` reports **22,469,519** (**2.5 MB headroom**). Both name the same quantity; both assert the same ceiling. ➡️ **The project\'s belief about its own headroom depends on which test you read, and the tighter one is the new one.** ⚠️ **f1615-1\'s disputed figures sit BETWEEN the two scales, so the unverified ~1.9 MB "growth" may be partly instrument mismatch rather than a regression — f1619-2 therefore does NOT close f1615-1, and that is the better outcome: it establishes that closing it requires naming the instrument first.** **RECOMMEND resolving the two sites before any further asset-diet tuning.** ' +

  '✅ **minds-and-rigs — THE OWNER\'S OWN COMMISSION, SHIPPED.** Two Field Book fan pages: **Minds** (models) and **Rigs** (harnesses), each an aggregate table (standings · contracts · crowns · best waves · declared cost · last active) expanding to the existing per-contract cells. ⭐ **Aggregate honesty is the design, not a disclaimer: sums cover only cells that DECLARE them, so an absent cost stays absent rather than becoming `0`.** 🏷️ **A vocabulary CORRECTION, not a rename** — `byStack` was labelled *"By rig"* while grouping by **MODEL**; it now reads **"Minds"** (`reader.ts:135-139`). ✓ **THE RANKING FIREWALL WAS PROVED, NOT ASSERTED:** the slice edits the file that mints county rank, so the drain ran `test:stats` **87** · `test:accounts` **43** · `test:mp` **462**, plus adjacent `lb-01-county-standings` + `milk-county-board` **34/34 both projects**, and audited **all 11 removed lines** in `standings.ts` individually — every one in the GET view-building path, **no POST-handler and no rank-minting line touched**. Plain-boot e2e green (Mistake #10), 390px containment **asserted not eyeballed** (`field-book.spec.ts:269`/`:280`). **[F-1620-6] non-blocking:** at DESKTOP width the aggregate table scrolls horizontally while free width sits unused beside it — the containment rule was written for 390px and applies at every width, and it bites exactly where the owner aimed (*"interested in the details"* — the details are the clipped columns). ' +

  '🔧 **[F-1620-9] MY OWN MERGE ROTTED THREE CITATIONS, THE LAST-ACT BATTERY CAUGHT IT, AND IT IS CURED IN THIS FIRE.** `48f217502` rewrote `field-book.spec.ts` (+135/−98) and **RENAMED two tests**, so three titled `BACKLOG` citations went stale; `test:citations` went **rc 1** on exactly the fire that caused it. All three re-keyed, re-run **rc 0** (291 CARRIES-TITLE), full `test:ledger-guards` **ALL GREEN**. 💡 **The reusable half sharpens F-1310-1 rather than repeating it: "cite by TITLE not line" defends against a merge inserting lines above you and is DEFENCELESS against a merge RENAMING the test** — the citation still fails, it just fails loudly instead of silently pointing at unrelated code, which is the guard working as designed. ⚠️ **A slice that renames a test is a citation-rot event even when its diff is small, entirely inside `e2e/`, and triggers no `test:node-guards` duty under F-1460-1.** ⓘ **Recorded deliberately WITHOUT proposing a new guard** — F-1300-4\'s existing order caught it on the first try. ' +

  '🆕 **AUTHORED 1 (the cap — three drains existed this fire, so the dry-board allowance of 2 did NOT apply). `f1620-1-cache-reuse-production-headers` → lane-c, QUEUED.** It is the probe F-1620-2 prescribes: run the same five-door walk against a **BUILT bundle with production-style headers** (reusing `playwright.preview.config.ts` — inventing a server is forbidden) and **report the exact `cache-control` read off a real response**, because ⚠️ *a run whose headers were not measured answers nothing, and measuring them is the entire difference from f1619-1.* It also folds in F-1620-1: `classify()` must read `status`, with a **REVALIDATED** bucket kept **separate from CACHE-HIT** (different costs; a future regression assertion will want them apart). **The stake is stated BOTH ways and the master forbids preferring either** — survives ⇒ a cure slice against `AdvanceStream.ts` is clearly worth funding; does not ⇒ the ladder stops here. 🔒 Gate topology unchanged per s1301: both tests live in a file the default run already reaches, and **adding an npm script is a STOP-and-report, not a judgement call**. 📮 **DISPATCH ORDER PER F-1424-3:** master + leaf + BACKLOG row committed FIRST (`85a1f52ad`) · lane-c refreshed SECOND (`behind=16 → 0`) · **all five citation keys re-proved IN THE LANE** THIRD · `cp` FOURTH, byte-identity confirmed by sha256 (`5866afd202775d7c`). ⚠️ **F-1425-2 bit me too and the lane caught nothing because I caught it first:** my first draft keyed the premise check to `the 25 MB town budget is asserted by` in `BACKLOG` — **it returns 0 there**, because that phrasing lives in my review, not in the ledger row. Re-keyed to two phrases proved `=1` against **the paths the master names**. ⓘ **One key is deliberately EXPECTED to return `0`** (`advance-stream-cache-reuse` in `package.json`), and the master says so out loud — it is the positive fact proving the spec has no dedicated npm script, which is *why* scope item 6 forbids adding one. ' +

  '📮 **STANDING DUTIES:** **GZ-01 — one item OWED and FILED** for `48f217502` (the only player-visible merge of the three; the other two are test + artifacts only). Checked rather than assumed: `git log --merges --since 06:00` returns my three plus `f5dbb5448`, which s1619 already verified as carried. · **TK-01 — nothing owed**: the 2026-08-09 digest was filed by s1618 at `marketing/outbox/ticker-digest-2026-08-09.md`; today\'s merges belong to tomorrow\'s digest · assayer `pending/` **0** · **ART untouched — no staging audit owed** · backup push at handoff · **DEPLOY RUN: this fire merged player-visible gameplay code** (the Field Book pages), so the deploy law applies rather than the bookkeeping-only skip. ' +

  '🧹 **HYGIENE:** all three done-moves prefixed with their merge hashes. Gate worktree `gate-s1620` created, used for all three drains, and **removed**; a 2.1 GB partial checkout orphaned by a timed-out first `worktree add` was cleared (my own debris, every file tracked, no factory history — the RETENTION LAW is untouched). ⚠️ **The two untracked masters `tasks/lane-agent-reels-emitter.md` / `lane-agentreel1-door-tape.md` were left UNTOUCHED for the FOURTH fire running, for the reason s1619 wrote down:** superseded 04:55/04:59 drafts of `tasks/lane-agent-reels.md`, whose thread is owner-blocked at **F-1617-1**, belonging to a live attended session — committing another writer\'s in-flight files is the F-1295-1 custody hazard with the roles reversed. **Leave them.** ' +

  '🏜️ **PIPELINE:** lane-c working on `f1620-1`; **lanes a, b and d are IDLE and I did not fill them** — my authoring cap was spent on the one master, and the natural next work for each is either owner-gated or needs a spec. **PIPELINE-DRY: lane-a, lane-b, lane-d (needs spec/owner).** ⓘ **The next fire has an unusually rich authorable board and should NOT need to sweep for candidates**: **F-1620-7** (reconcile or rename the two `townResponseBytes` sites, then restate f1615-1 against a named instrument — recommended BEFORE further asset-diet tuning), **F-1620-4** (the prefetch fires **2–3× per URL** carrying the full asset each time — sequence it AFTER `f1620-1` so the cure is measured against production headers), **F-1620-6** (desktop-width Field Book layout), **F-1620-3** (per-URL byte accounting), **F-1620-8** (why desktop and mobile `saveData` deltas differ by 37% — the per-URL tables hold the unread answer). All carry **GATE: none owed to the owner.** ' +

  '🔭 **NEXT FIRE (A) DRAIN `f1620-1` from lane-c when it finishes — it decides whether a much larger performance slice exists.** Read the **REVALIDATED vs DOUBLE-DOWNLOAD** split and the **measured `cache-control` per arm**; a run that did not measure its headers has not answered the question, whatever its table says. **(B)** author against **F-1620-7** — it is the cheapest real finding on the board and it gates the honesty of every future asset-diet number. **(C)** lane-b and lane-d want either a spec slice or the F-1617-1 ruling. **(D)** the f1615-1 runner\'s explicitly UNVERIFIED `240/246` `--repeat-each=3` and `22/28` adjacent tallies remain unconfirmed drain-side; **F-1618-2 says do not try to settle them in a fire shell.** ' +

  '🔺 **OWNER\'S DESK — 14 awaiting a word.** ⓵ `desk-state-audit --status` against s1619\'s archived line-1: **`CLOSED=0 · OPEN=0 · BOTH=0 · OPEN-DESK-ONLY=14 · UNRECORDED=0`** — nothing carried should have been dropped and no carried item is a ghost. **All nine of my findings (F-1620-1 … F-1620-9) say GATE: none owed to the owner** — they are measurements and engineering questions, not design forks. ' +
  '🔺 **F-1617-1 OPEN** — the tape format cannot represent an agent run; you already ruled *emit+backfill*, what is open is only the REPRESENTATION: **(a)** a bounded `agent_orders` tape action taught to the reel player (**REC**) or **(b)** a separate standing-order log ' +
  '🔺 **F-DOOR-6 OPEN** — only **(c)**, publishing build zones in the map block, is yours ' +
  '🔺 **F-1608-2 OPEN** — the Trestle/Incline railcars are byte-identical to the Hill Mine one just tuned; *"probably the same"* is not a ruling ' +
  '🔺 **F-1193-3 OPEN** — fourth premise spent and failed; **(a)** retire the diagonal ambition (REC) or **(b)** fund a premise changing the FIGURE-SIDE instruction ' +
  '🔺 **F-1501-3 OPEN** — 582 files / 527.89 MB in no object database ' +
  '🔺 **F-1601-1 OPEN** — the `gateClass` column needs an attended nod ' +
  '🔺 **F-1510-1 OPEN** — mechanical gate MET s1609; *keep the go-around* (REC) or *the complaint moved* ' +
  '🔺 **F-E2S-3 OPEN** — socket half needs its census-stream slice specced ' +
  '🔺 **F-1536-2 OPEN** — census done; renames + dynamic panel need a word ' +
  '🔺 **F-1591-1 OPEN** — Arm 0\'s gate MET, clamp unconfirmed below the knee; F-1593-2 counsels parking ' +
  '🔺 **F-1507-1 OPEN** — both shells on one node version ' +
  '🔺 **F-E2S-4 OPEN** — genuinely owner-gated ' +
  '🔺 **F-1101-1 OPEN** — parked KNOWN-INCOMPLETE by your ruling ' +
  '🔺 **F-1166-1 OPEN** — awaiting your word since s1166.';

const p = 'STATUS.md';
const L = fs.readFileSync(p, 'utf8').split('\n');
const prevLock = L[0];
if (!prevLock.startsWith('ACTIVE')) throw new Error('line 1 is not my ACTIVE lock: ' + prevLock.slice(0, 80));

L[0] = line1;
// Archive MY lock line as a bullet, immediately above the inherited s1619 archive.
const idx = L.findIndex((l) => l.startsWith('- **s1619 handoff (line-1 archive):**'));
if (idx < 0) throw new Error('s1619 archive bullet missing — would strand the inherited handoff');
L.splice(idx, 0, '- **s1620 lock line (archived):** ' + prevLock);
fs.writeFileSync(p, L.join('\n'));

const after = fs.readFileSync(p, 'utf8');
const n = (after.match(/- \*\*s1619 handoff \(line-1 archive\):\*\*/g) || []).length;
console.log('s1619 archive bullet count (expect 1):', n);
console.log('line1 length:', after.split('\n')[0].length);
