const fs = require('fs');
const p = 'STATUS.md';
const s = fs.readFileSync(p, 'utf8');
const nl = s.indexOf('\n');
const line1 = s.slice(0, nl); // current s622 ACTIVE line
const rest = s.slice(nl + 1);

const handoff = "Last updated: 2026-07-16T05:45:00Z s622 handoff, lock CLEARED — **DRY STREAK BROKEN (was 23 consecutive).** Attended re-queued the IMPACT-LAW research master to lane-b and the RUNNER IS LIVE on it; this fire HELD — did NOT touch lane-b (live attended/runner thread, §7.6 + coexistence). **FRESH VERIFY (all this fire):** lanes m3/m4/e2-arsenal/perf all **0-ahead** pre-run; `tasks/queue`=**1** (the live `lane-b/research-impact-law.md`); `tasks/running` holds the lane-b marker + `lane-b.pid` (codex exec **pid 89238/89251**, gpt-5.6-sol high, started **05:38**); assayer `pending/`=0; no `tasks/CODEX-WALL`; `origin/main..main`=0. **⚠ VERSION-SKEW (drain-critical):** the in-flight `running/` copy (053820) is the OLDER **v1** master — it authors **'BANKED'** player wording; the QUEUE file (committed **43779d64**) is the CORRECTED **v2** that supersedes it — player-facing word = **'Unlocks:'**, grep-bans bank(s)/staked from player surfaces. So the CURRENT run lands SUPERSEDED (BANKED) copy; the queued v2 is self-correcting (its pre-flight: *if a prior run landed BANKED/STAKED, REPLACE with Unlocks:*). **⚠ STALE-BASE:** lane/m4 base = **3307f00a**, main tip = **43779d64** (2 intervening player-facing wording commits 5602b3fd STAKED + 43779d64 Unlocks:) → the eventual drain is a stale-base graft (Mistake #15): classify LANE-TOUCHED vs MAIN-MOVED per file, 3-way where both moved, NEVER blind-copy. **⏰ NEXT FIRE:** **(A)** if lane-b run STILL LIVE (codex pid present / no done-move) → **HOLD again**, do NOT touch lane-b, do NOT monitor (fire-cannot-hold-bounded-watch). **(B)** when lane-b done-moves → **DRAIN it, but FIRST grep the output/review for BANKED vs Unlocks:** — do NOT drain v1 BANKED output as final; the **v2 (Unlocks:) end-state is the deliverable** (the runner should pick up queue v2 next and self-correct — verify before treating any BANKED output as done). Player-visible research UI → **GZ item on merge**. **(C)** **TICKER DUE:** first fire after **06:00 local** (≈15 min out) compiles 07-15 merges → `marketing/outbox/ticker-digest-2026-07-15.md` (07-15 = e8/e9/e10 board-gated research charts → likely thin digest); if still <06:00, skip. **(D)** other lanes a/c/d (m3/e2-arsenal/perf) 0-ahead, queues empty, ladder EXHAUSTED / **PIPELINE-DRY** — no refill, needs owner ruling or new spec. **BACKUP:** this fire pushes at handoff. **DEPLOY:** merged nothing → SKIP. **GZ:** none this fire. **⚠ OWNER'S DESK (unchanged):** (i) DEPLOY player-visible debt (`scripts/deploy.sh` attended-gated); (ii) town flat-buildings repro if seen in NORMAL play; (iii) town-era-switch items; (iv) art-boss-plates retakes in `worktrees/art` await keep/discard; (v) e6–e10 research node tables await owner ratification; (vi) 🔴 PIPELINE-DRY other lanes until the next arc opens. **6 GAZETTE items queued this week.**";

const archived = "- **s622 ACTIVE (line-1 archive):** " + line1;
fs.writeFileSync(p, handoff + "\n" + archived + "\n" + rest);
console.log("handoff written");
