import fs from 'node:fs';

const prev = fs.readFileSync('/tmp/s1497-line1.txt', 'utf8').trim();
if (!prev.startsWith('Last updated: 2026-08-06T21:16Z s1497 handoff')) {
  throw new Error('banked s1497 line-1 is not what I expect — refusing to archive the wrong line');
}

const line1 = [
  'Last updated: 2026-08-06T22:04Z s1498 handoff, lock CLEARED — 🟩 **TWO DRAINS, SIX OF EIGHT OFF THE MILK PILE — `milk/twin-sockets` MERGED `c41ba89d` AND `milk/county-board` MERGED `38791378`.**',
  '✅ **DRAIN 1 — THE TWIN SOCKETS, the 13-hunk merge s1497 deliberately refused to rush.** Both era sockets are on main: `src/sim/DeepwaterSocket.ts` and `src/sim/AtomicSocket.ts`, each in the browser\'s own tick order. **ZERO admissions, and the zero IS the deliverable** — `SUPPORTED_CONTRACTS` untouched on all eight contracts. `e6-showroom` secures at wave 20 deterministically and that is a **FALSE GREEN**: with wrangle live an exhausted machine is undamageable AND harmless AND still alive, so from wave 6 all 60 living enemies are exhausted, `Balance.waves.aliveCap` is 60, `WaveSystem` refuses to spawn, and the "win" is against an empty board for fourteen waves. Admitting it would have pinned a determinism hash on a deadlock. `e5-deepwater-claim` cannot be admitted at ANY wiring effort — `DredgeQueenBossSystem` builds sprites in **instance field initializers** (`:77-80`, helper `:736`), so it throws outside a browser before its own `enabled` flag is read, and it owns the contract\'s only exit.',
  '🗺️ **s1497\'s banked map was RE-MEASURED before it was trusted (F-1497-1) and it held exactly** — main had moved only `STATUS.md` and `artifacts/` since. **Three resolutions the next reader should not re-derive.** ① **F-ID COLLISION:** `milk/deepwater-surgery` and `milk/twin-sockets` were authored in parallel against the same E5 census and **both minted `F-ER01-E5-5`** for different findings; neither branch could see the other. The socket-shape stub keeps the number (three live citations name it); the socket pass\'s finding is renumbered **`F-ER01-E5-7`** in place. ② **TWO STALE ASSERTS DROPPED:** `er01-e5-census.spec.ts` asserted the Claim carries **no** `engineDependencies` — true at the branch\'s base, false once `deepwater-surgery` landed the declaration. Main\'s ADMISSION GATE 1 is **strictly stronger** (exact `dep` name, all four contracts, vs status-only for three), so the branch\'s two lines were superseded with the reasoning left at the call site. **Keeping them would have redded.** ③ **`BROKEN: 1 of 4` STRUCK, NOT DELETED** — the Regatta six-vs-five beacon defect was cured at `7bfd62ee`; resolved to **0 of 4** under a bridging banner naming why it was stale. The E6 census was rebuilt deliberately from both blobs rather than untangling git\'s interleaving: socket-live findings LIVE, `saga-surgeon`\'s declaration-cure banners and pre-socket originals RETAINED beneath each, main-only `F-MILK-SS-1`/`F-MILK-SS-2` preserved whole.',
  '🧪 **GATES (drain 1), detached `gate-s1498` §3.0b, `--workers=1`, both projects:** tsc rc=0 · build 994ms · `er01-e5`+`er01-e6` **16/16** · adjacent `er01` e2/e3/e4/e7/e8/e9/e10 **56/56** · `test:node-guards` **341 tests / 338 pass / 0 fail / 3 skipped** (F-1460-1 fired — diff touches `src/sim/`+`src/agent/`) · control `gr-sim` **10/10 pass 0 fail** (the review pinned **9/9**; main added the F-1493-2 Baron drift pin since, so the count GREW and nothing redded) · plain-boot **14/14** desktop+390px, zero console/page errors.',
  '✅ **DRAIN 2 — THE COUNTY BOARD, and this one is PLAYER-VISIBLE.** Posse standings + watch-this-run: a posse ranks only against posses its own size (the solo board is byte-identical to before), every row with a reel carries a handle the visitor can play back, and the field book — kept off the ladder on purpose — is the only place a declared stack is seen. **GATES:** tsc rc=0 · build 1.23s · own spec **14/14** (three of them PLAIN-BOOT, answering Mistake #10 inside the slice) · adjacent tape-01/tape-02/f1297-2/run3d-lantern-post/profile-first-boot **32/32** · `test:node-guards` **341/338 pass/0 fail/3 skipped**. 🔒 **`functions/api/standings.ts` is a new PUBLIC endpoint and I read it rather than assuming**: allowlist key validation on every nested shape, CORS allowlist, per-IP AND per-anon rate limiting, 64KB tape / 100-row caps, regex-validated hashes, KV keys built only from validated ids, no secrets client-side. **AP-06 species-blindness is structural, not conventional** — `boardRow` hands the ladder NAMES only. 📰 **GZ-01 item filed** and **DEPLOY ran**: published + verified `4c38f967` at https://gold-rush-3in.pages.dev. Backup pushed to origin, OK.',
  '🟥 **F-1498-1 (NEW): two branches authored in parallel against one shared document MINT THE SAME F-ID, and neither can see it — the collision surfaces only at the SECOND merge.** Different from the known author-and-drain collision: that one is single-actor with a same-fire cure; this is **concurrency** — a sequence number taken from a *snapshot* of a shared file is unique only against that snapshot. **It reds NOTHING** (markdown tolerates duplicate headings; tsc, build, every spec and all 341 guards were green with both `E5-5`s present), so the only detector is a human reading the merge. ✅ **SWEPT, NOT ASSUMED: I parsed every `### F-<id>` heading across all of `docs/bench/*.md` — zero duplicates remain fleet-wide**, so this was the only live instance. The producers are still live (two milk branches left), so re-run that one-line sweep on every drained census.',
  '⚠️ **AND A NEAR-MISS WORTH MORE THAN THE FINDING: my first `county-board` merge was ABORTED AND REDONE.** The gate worktree was still detached at the twin-sockets **merge** commit — one behind main\'s twin-sockets **bookkeeping** commit — so the `goals.json` union **silently dropped the `milk-twin-sockets` leaf I had just written**. It was caught only because the resolution script asserted the merged JSON still contained **named leaves**, not merely that it **PARSED**: a parse-only check goes green on a lossy union, because valid JSON is exactly what a dropped object leaves behind. Aborted, re-detached to main HEAD, redone, all four leaves re-verified PRESENT. **Assert on CONTENT you can name, never on well-formedness.**',
  'ⓘ **Duties:** assayer pending **empty** · ticker digest for 2026-08-05 already filed by s1493, nothing owed today · drain 1 correctly filed **no** gazette item (`src/game/` byte-unchanged, sim/agent only) while drain 2 owed one and has one. 🧹 `gate-s1498` removed after a lossless audit (HEAD identical to main, **zero** commits main lacks, empty staged index); its six merge-resolution scripts were **salvaged into git first** (Retention Law) at `857d16af`. **`gate-s1455` untouched — it is F-1494-1 on your desk.**',
  '📌 **NEXT FIRE — I RE-MEASURED BOTH REMAINING BRANCHES SO YOU INHERIT FACTS, NOT GUESSES (F-1497-1).** **(A) 🥇 `milk/steamworks-rehearsal` FIRST, not last** — 113 files but **exactly ONE overlap with main (`tasks/BACKLOG.md`)**, so it is size, not risk, and s1497\'s "mostly tapes" read is confirmed. Cheapest real merge on the board. **(B) `milk/agent-seat` LAST — it is the only genuine graft: 5 overlaps, and they are the dangerous kind** — `src/sim/HeadlessContractSim.ts` (**which twin-sockets just rewrote — expect a real conflict at the tick-order seam**), plus `public/skill.md` (watch `skillmd-guard`) and `package.json` (watch `gate-caller-audit`: a new npm script must be rooted or grandfathered). Budget a whole shift. **(C)** the `e1-drill-yard` fixture red (`agent-view.spec.ts:264`/`:297`, gate BOTH projects — F-1496-1) is still cheap, still fire-authorable, still unowned. **(D)** author `e9-dome-basin` — `twin-sockets` has landed, so its stated precondition is now met. **(E) still unresolved, not resolved against you:** s1495\'s attended-word request on F-1481-2\'s literal reading, and `tasks/BACKLOG.md`\'s spent *"fires\' ladder stays E3-only"* rationale.',
  '🔺 **OWNER\'S DESK — 11 awaiting a word (1 added this fire, none resolved).** 🔺 **F-MTS-2 (ADDED THIS FIRE — it rode in on the twin-sockets merge and is the highest-leverage item on this list)** — **two epochs, socketed independently, both land on the same missing thing: `AgentGameAdapter` has no verb for their defining action.** `src/agent/ToolSurface.ts:82` carries exactly `placeBuilding`, `panAt`, `repair`, `chaseMark`, `collectXp`, `collectGold`. E6 Atomic needs **capture** — without it the board deadlocks (measured, above). E5 needs **boat-build** and **reanchor**. A new verb in the agent grammar is a governed-surface decision, so the shift filed rather than fixed it. **REC: rule on the CAPTURE verb first — it alone unblocks 2 of 4 Atomic contracts**, where the two boat verbs unblock nothing until the Dredge-Queen\'s presentation is made lazy. 🔺 **F-MILK-SS-3** Dust Flats says *"four surveyed fields"* and authors **three**. Add a 4th (gameplay/balance) or fix the prose (**one reversible word — but it permanently erases the only record a fourth was ever intended**)? **REC: if the Dust Flats plays well as three, take the prose fix.** 🔺 **F-MSD-1** 13 of 25 campaign maps cannot be opened (`ContractFamilies.ts:1328` refuses `harvestAnchors: []`), so the F-1368-1 row asks you for 25 verdicts and **12 are possible**. **REC: (a) verdict the 12.** 🔺 **F-MSD-2** five reuse maps ship 25 bespoke landmark `.glb` the game can never mount — was the reuse ruling meant to cover **dressing** too? 🔺 **F-1494-1** remove `gate-s1455/` and reclaim 14 GB? Provably lossless. **REC: remove.** 🔺 **F-1493-3** Hill Mine: a Railcar dying at wave 14 under a 100,000-HP rig — acceptable tuning? **REC: accept.** 🔺 **F-1475-1** e3-fairground diagnostics-only construction path — **REC: (c) a `diagnostic:true` boot flag**; F-1495-1 raises its price: one word unblocks the construction path for **30 contracts**. 🔺 **F-1096-2** rf-34 hero-Y: (A) merge as-is [rec] or (B) terrain-visualY authoritative. 🔺 **F-1166-1** vp-02e jumper: (a) accept coarse [rec] or (b) real 8-way art. 🔺 **F-1294-1** calibrate-suite-workers-v2 — worth a v3? [rec: RETIRE]. 🔺 **f1328-1** drill-yard: does a byte-stable fixture of a wrong derivation bless it or catch it? **NEW this fire, non-blocking, no word needed:** every merge resolution above is reversible with one word. **Robin owes (unchanged, never blocking):** turret-feel + water-feel playtests, Mac full-regression evidence, favicon 16px eyeball.',
].join(' ');

const p = 'STATUS.md';
const lines = fs.readFileSync(p, 'utf8').split('\n');
lines[0] = line1;

// Archive s1497's line-1, which the lock commit dropped. Insert directly after the law bullets begin.
const at = lines.findIndex((l) => l.startsWith('- **s'));
if (at < 0) throw new Error('no archive bullet block found');
lines.splice(at, 0, `- **s1497 handoff (line-1 archive):** ${prev.replace(/^Last updated: /, '')}`);
fs.writeFileSync(p, lines.join('\n'));

const txt = fs.readFileSync(p, 'utf8');
const l1 = txt.split('\n')[0];
console.log('archive bullets for s1497:', (txt.match(/s1497 handoff \(line-1 archive\)/g) || []).length);
console.log("desk header on line-1:", /OWNER'S DESK/.test(l1));
console.log('line-1 length:', l1.length);
